# Generated by Django 5.1.5 on 2025-12-11 07:28

import human_resources.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIncomingCommunication',
            fields=[
                ('transmittal_number', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('datetime_received', models.DateTimeField(null=True)),
                ('sender', models.CharField(max_length=99, null=True)),
                ('subject', models.TextField(max_length=499, null=True)),
                ('scan', models.FileField(blank=True, null=True, upload_to=human_resources.functions.filepath_extincomingcomm)),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingCommunication',
            fields=[
                ('transmittal_number', models.CharField(blank=True, max_length=13, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('nature_of_content', models.TextField(blank=True, max_length=99, null=True)),
                ('recipient', models.CharField(default='', max_length=30)),
                ('original_copy', models.FileField(blank=True, null=True, upload_to=human_resources.functions.filepath_original)),
                ('receiving_copy', models.FileField(blank=True, null=True, upload_to=human_resources.functions.filepath)),
                ('cancel', models.BooleanField(default=False)),
            ],
        ),
    ]
