# Generated by Django 5.2.9 on 2025-12-15 05:59

import human_resources.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('transmittal_number', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('nature_of_content', models.TextField(blank=True, max_length=99, null=True)),
                ('recipient', models.CharField(default='', max_length=30)),
                ('original_copy', models.FileField(blank=True, null=True, upload_to=human_resources.functions.filepath_original)),
                ('receiving_copy', models.FileField(blank=True, null=True, upload_to=human_resources.functions.filepath)),
                ('cancel', models.BooleanField(default=False)),
            ],
        ),
    ]
