# Generated by Django 5.2.9 on 2025-12-15 07:25

import human_resources.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliciesAndGuideline',
            fields=[
                ('transmittal_number', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('nature_of_content', models.TextField(blank=True, max_length=99, null=True)),
                ('concerned_personnel', models.TextField(blank=True, max_length=99, null=True)),
                ('date_of_effectivity', models.DateField(null=True)),
                ('date_of_expiry', models.DateField(null=True)),
                ('signed_copy', models.FileField(blank=True, null=True, upload_to=human_resources.functions.filepath_policies)),
                ('cancel', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='letter',
            name='original_copy',
            field=models.FileField(blank=True, null=True, upload_to=human_resources.functions.filepath_letter_original),
        ),
        migrations.AlterField(
            model_name='letter',
            name='receiving_copy',
            field=models.FileField(blank=True, null=True, upload_to=human_resources.functions.filepath_letter_receiving),
        ),
    ]
