# Generated by Django 5.2.9 on 2025-12-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_policiesandguideline_alter_letter_original_copy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policiesandguideline',
            name='concerned_personnel',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
