# Generated by Django 5.2.9 on 2025-12-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_alter_policiesandguideline_concerned_personnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policiesandguideline',
            name='date_of_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policiesandguideline',
            name='nature_of_content',
            field=models.TextField(max_length=99, null=True),
        ),
    ]
