# Generated by Django 5.2.9 on 2025-12-16 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0005_alter_policiesandguideline_date_of_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policiesandguideline',
            name='update_existing',
            field=models.ForeignKey(blank=True, help_text='Select the existing policy that this entry updates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to='human_resources.policiesandguideline', verbose_name='Update Existing'),
        ),
        migrations.AlterField(
            model_name='policiesandguideline',
            name='signed_copy',
            field=models.FileField(blank=True, null=True, upload_to='policies/'),
        ),
    ]
