# Generated by Django 3.0.6 on 2020-05-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ['ore_class', 'count']},
        ),
    ]
