# Generated by Django 5.0.6 on 2024-07-08 10:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_alter_providerequipmentrequirementdetail_activity'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManilaGpsWebsocketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.SmallIntegerField(blank=True, null=True)),
                ('battery_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('call_time', models.DateTimeField(blank=True, null=True)),
                ('connection_status', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('heading', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_blocked', models.DateTimeField(blank=True, null=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('movement_status', models.TextField(blank=True, null=True)),
                ('network_name', models.TextField(blank=True, null=True)),
                ('signal_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('speed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tracker_id', models.PositiveIntegerField()),
                ('update_battery', models.DateTimeField(blank=True, null=True)),
                ('update_gps', models.DateTimeField(blank=True, null=True)),
                ('update_gsm', models.DateTimeField(blank=True, null=True)),
                ('update_last', models.DateTimeField(blank=True, null=True)),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipment')),
            ],
        ),
    ]
