# Generated by Django 3.2 on 2021-06-15 08:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_alter_tripdetail_interval_class'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchored', models.DateTimeField()),
                ('latitude_degree', models.PositiveSmallIntegerField(default=9)),
                ('latitude_minutes', models.DecimalField(decimal_places=5, max_digits=7)),
                ('longitude_degree', models.PositiveSmallIntegerField(default=125)),
                ('longitude_minutes', models.DecimalField(decimal_places=5, max_digits=7)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('laydays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.laydaysstatement')),
            ],
            options={
                'ordering': ['anchored'],
            },
        ),
        migrations.AddConstraint(
            model_name='anchorage',
            constraint=models.CheckConstraint(check=models.Q(latitude_minutes__gte=0), name='lat_floor'),
        ),
        migrations.AddConstraint(
            model_name='anchorage',
            constraint=models.CheckConstraint(check=models.Q(latitude_minutes__lt=60), name='lat_ceiling'),
        ),
        migrations.AddConstraint(
            model_name='anchorage',
            constraint=models.CheckConstraint(check=models.Q(longitude_minutes__gte=0), name='lon_floor'),
        ),
        migrations.AddConstraint(
            model_name='anchorage',
            constraint=models.CheckConstraint(check=models.Q(longitude_minutes__lt=60), name='lon_ceiling'),
        ),
    ]
