# Generated by Django 4.0 on 2022-02-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='exposure_rate',
            field=models.IntegerField(blank=True, help_text='Percentage of blocks either exposed or excavated.', null=True),
        ),
    ]
