# Generated by Django 4.2 on 2023-07-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentlocation',
            name='heading',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentlocation',
            name='satellites',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentlocation',
            name='speed',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='equipmentlocation',
            index=models.Index(fields=['time_stamp'], name='location_eq_time_st_8df0cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentlocation',
            constraint=models.UniqueConstraint(fields=('equipment', 'time_stamp'), name='unique_equipment_location_timestamp'),
        ),
    ]
