# Generated by Django 3.0.6 on 2020-05-29 17:09

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20200529_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='with_layout',
        ),
        migrations.AddField(
            model_name='cluster',
            name='layout_date',
            field=models.DateField(blank=True, help_text='Date when the cluster is laid out on the field. When this\n        date is set, the date scheduled cannot be changed. This date cannot be\n        filled out when the date scheduled is still empty.', null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='date_scheduled',
            field=models.DateField(blank=True, help_text='Date when the cluster geometry is finalized. When this\n        date is set, the geometry cannot be changed.', null=True),
        ),
        migrations.AddConstraint(
            model_name='cluster',
            constraint=models.CheckConstraint(check=models.Q(layout_date__gte=django.db.models.expressions.F('date_scheduled')), name='layout_later_than_schedule'),
        ),
    ]
