# Generated by Django 4.2 on 2023-08-07 23:02

import custom.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_equipmentlocation_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BLGU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3125)),
            ],
            options={
                'verbose_name': 'Barangay Political Boundary',
                'verbose_name_plural': 'Barangay Political Boundaries',
            },
        ),
    ]
