# Generated by Django 3.1.7 on 2021-03-13 08:02

import custom.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_cluster_dumping_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpile',
            name='name',
            field=custom.fields.PileField(max_length=100, unique=True),
        ),
    ]
