# Generated by Django 5.0.6 on 2024-07-09 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_manilagpswebsocketdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manilagpswebsocketdata',
            options={'verbose_name': 'Manila GPS Websocket Data', 'verbose_name_plural': 'Manila GPS Websocket Data'},
        ),
    ]
