# Generated by Django 3.0.3 on 2020-03-03 07:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_cluster_date_scheduled'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_surveyed', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3125)),
            ],
        ),
        migrations.AddIndex(
            model_name='roadarea',
            index=models.Index(fields=['date_surveyed'], name='location_ro_date_su_e4d5d6_idx'),
        ),
    ]
