# Generated by Django 3.1.7 on 2021-03-13 08:26

import custom.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20210313_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpile',
            name='name',
            field=custom.fields.NameField(max_length=100, unique=True),
        ),
    ]
