# Generated by Django 4.2 on 2023-08-14 18:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_blgu'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaulingEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_begin', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('time_stamp', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'location_haulingequipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoadingEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_begin', models.DateTimeField()),
                ('ts_end', models.DateTimeField()),
                ('time_stamp', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'location_loadingequipment',
                'managed': False,
            },
        ),
    ]
