# Generated by Django 3.0.3 on 2020-03-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20200303_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadarea',
            name='date_surveyed',
            field=models.DateField(unique=True),
        ),
    ]
