# Generated by Django 3.0.3 on 2020-03-03 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20200303_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='road',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.RoadArea'),
        ),
    ]
