# Generated by Django 3.0.3 on 2020-03-03 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_cluster_road'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='road',
            field=models.ForeignKey(blank=True, help_text='Road used to adjust the cluster geometry.', null=True, on_delete=django.db.models.deletion.PROTECT, to='location.RoadArea'),
        ),
    ]
