# Generated by Django 4.0.6 on 2022-08-03 07:07

import custom.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material_management.legacyitemtype')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyGoodsReceivedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=10)),
                ('transaction_date', models.DateField()),
                ('entry_date', models.DateField()),
                ('purchase_order', models.CharField(max_length=8)),
                ('invoice_number', models.TextField(blank=True, null=True)),
                ('invoice_amount', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('purchase_order_price', models.FloatField()),
                ('discount', models.FloatField(blank=True, null=True)),
                ('net_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material_management.legacymaterial')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material_management.legacyvendor')),
            ],
            options={
                'ordering': ['transaction_date', 'entry_date', 'reference_number'],
            },
        ),
        migrations.CreateModel(
            name='LegacyGoodsIssuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=10)),
                ('transaction_date', models.DateField()),
                ('entry_date', models.DateField()),
                ('order_type', models.CharField(max_length=10)),
                ('cost_center', models.CharField(blank=True, max_length=8, null=True)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('quantity', models.FloatField()),
                ('unit_cost', models.FloatField(blank=True, null=True)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material_management.legacymaterial')),
            ],
            options={
                'ordering': ['transaction_date', 'entry_date', 'order_number'],
            },
        ),
    ]
