# Generated by Django 4.2 on 2023-05-08 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_alter_equipment_month_of_registration'),
        ('material_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IFCU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('liters', models.FloatField()),
                ('measurement_document', models.PositiveIntegerField(unique=True)),
                ('material', models.CharField(choices=[('A', 'ADBLUE'), ('D', 'DIESEL'), ('G', 'GASOLINE')], max_length=1)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipment')),
            ],
        ),
    ]
