# Generated by Django 4.0.6 on 2022-08-17 01:39

import custom.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_management', '0002_materialgroup_materialtype_unitofmeasure_valuation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'ordering': ['unit'], 'verbose_name_plural': 'units of measure'},
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='name',
            field=custom.fields.NameField(max_length=3),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='unit',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
