# Generated by Django 3.1.11 on 2021-06-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.CharField(choices=[('1', 'CKDI'), ('2', 'TRGC'), ('3', 'SDMC'), ('4', 'SKAFF'), ('5', 'HPK'), ('6', 'NICKELBASE')], max_length=32, null=True)),
                ('purpose', models.CharField(choices=[('1', 'Shipment'), ('2', 'Rental'), ('3', 'Limonite'), ('4', 'Envi')], max_length=32, null=True)),
                ('amount', models.IntegerField()),
                ('tonnage', models.IntegerField(blank=True, null=True)),
                ('operating_hours', models.IntegerField(blank=True, null=True)),
                ('received_by', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to', models.CharField(blank=True, choices=[('1', 'Sir Jun'), ('2', 'Accounting/Advance'), ('3', 'Mines'), ('4', 'Others')], max_length=32, null=True)),
                ('sent_by', models.DateTimeField(blank=True, null=True)),
                ('notes_sent', models.TextField(blank=True, null=True)),
                ('received_by', models.DateTimeField(blank=True, null=True)),
                ('notes_received', models.TextField(blank=True, null=True)),
                ('billing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.billingtracker')),
            ],
        ),
    ]
