# Generated by Django 4.2.7 on 2023-11-13 03:47

import billing.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.CharField(choices=[('CKDI', 'CKDI'), ('TRGC', 'TRGC'), ('SDMC', 'SDMC'), ('HPK', 'HPK'), ('NB', 'NICKELBASE'), ('POL', 'POLARIS'), ('ETER', 'ETER')], max_length=32, null=True)),
                ('purpose', models.CharField(choices=[('SHIP', 'Shipment'), ('REN', 'Rental'), ('LIM', 'Limonite'), ('ENV', 'Envi')], max_length=32, null=True)),
                ('specification', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('amount', models.FloatField()),
                ('tonnage', models.FloatField(blank=True, null=True)),
                ('operating_hours', models.FloatField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=32, null=True)),
                ('fileup', models.FileField(blank=True, null=True, upload_to=billing.models.filepath)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shipment.laydaysstatement')),
            ],
        ),
        migrations.CreateModel(
            name='CMBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_year', models.CharField(default=2023, max_length=4, null=True)),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='1', max_length=9, null=True)),
                ('half', models.CharField(choices=[('1', '1st'), ('2', '2nd')], default='1', max_length=3, null=True)),
                ('amount', models.FloatField(null=True)),
                ('tonnage', models.FloatField(null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Contract Mining Billing',
                'verbose_name_plural': 'Contract Mining Billings',
            },
        ),
        migrations.CreateModel(
            name='BillingAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_from', models.CharField(blank=True, choices=[('Sir Jun', 'Sir Jun'), ('Accounting/Advance', 'Accounting/Advance'), ('Mines', 'Mines'), ('Envi', 'Envi'), ('Others', 'Others')], max_length=32, null=True)),
                ('received_by', models.DateTimeField(blank=True, null=True)),
                ('notes_received', models.TextField(blank=True, null=True)),
                ('sent_to', models.CharField(blank=True, choices=[('Sir Jun', 'Sir Jun'), ('Accounting/Advance', 'Accounting/Advance'), ('Mines', 'Mines'), ('Envi', 'Envi'), ('Others', 'Others')], max_length=32, null=True)),
                ('sent_by', models.DateTimeField(blank=True, null=True)),
                ('notes_sent', models.TextField(blank=True, null=True)),
                ('billing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.billingtracker')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentBillingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('tonnage', models.FloatField(null=True)),
                ('onboard_handling_amount', models.FloatField(blank=True, null=True)),
                ('onboard_handling_ton', models.FloatField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.shipmentbilling')),
            ],
            options={
                'unique_together': {('contractor', 'shipment')},
            },
        ),
    ]
