# Generated by Django 4.0.4 on 2022-04-21 10:43

import billing.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.CharField(choices=[('CKDI', 'CKDI'), ('TRGC', 'TRGC'), ('SDMC', 'SDMC'), ('HPK', 'HPK'), ('NB', 'NICKELBASE'), ('POL', 'POLARIS'), ('ETER', 'ETER')], max_length=32, null=True)),
                ('purpose', models.CharField(choices=[('SHIP', 'Shipment'), ('REN', 'Rental'), ('LIM', 'Limonite'), ('ENV', 'Envi')], max_length=32, null=True)),
                ('specification', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('amount', models.FloatField()),
                ('tonnage', models.FloatField(blank=True, null=True)),
                ('operating_hours', models.FloatField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, max_length=32, null=True)),
                ('fileup', models.FileField(blank=True, null=True, upload_to=billing.models.filepath)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_from', models.CharField(blank=True, choices=[('Sir Jun', 'Sir Jun'), ('Accounting/Advance', 'Accounting/Advance'), ('Mines', 'Mines'), ('Envi', 'Envi'), ('Others', 'Others')], max_length=32, null=True)),
                ('received_by', models.DateTimeField(blank=True, null=True)),
                ('notes_received', models.TextField(blank=True, null=True)),
                ('sent_to', models.CharField(blank=True, choices=[('Sir Jun', 'Sir Jun'), ('Accounting/Advance', 'Accounting/Advance'), ('Mines', 'Mines'), ('Envi', 'Envi'), ('Others', 'Others')], max_length=32, null=True)),
                ('sent_by', models.DateTimeField(blank=True, null=True)),
                ('notes_sent', models.TextField(blank=True, null=True)),
                ('billing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.billingtracker')),
            ],
        ),
    ]
