# Generated by Django 5.1.5 on 2026-02-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmbilling',
            name='billing_year',
            field=models.CharField(default=2026, max_length=4, null=True),
        ),
    ]
