# Generated by Django 4.2 on 2023-07-10 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_year', models.CharField(default=2023, max_length=4, null=True)),
                ('month', models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='1', max_length=9, null=True)),
                ('half', models.CharField(choices=[('1', '1st'), ('2', '2nd')], default='1', max_length=3, null=True)),
                ('amount', models.FloatField(null=True)),
                ('tonnage', models.FloatField(null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Contract Mining Billing',
                'verbose_name_plural': 'Contract Mining Billings',
            },
        ),
    ]
