# Generated by Django 3.1.11 on 2021-06-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingtracker',
            name='received_by',
        ),
        migrations.AddField(
            model_name='billingtracker',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='billingtracker',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
