# Generated by Django 4.2.7 on 2024-03-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmbilling',
            name='billing_year',
            field=models.CharField(default=2024, max_length=4, null=True),
        ),
    ]
