# Generated by Django 3.1.11 on 2021-06-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20210601_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingtracker',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='billingtracker',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
