# Generated by Django 4.2 on 2023-07-18 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_alter_laydaysstatement_vessel_voyage'),
        ('organization', '0001_initial'),
        ('billing', '0002_cmbilling'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('tonnage', models.FloatField(null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='shipment.laydaysstatement')),
            ],
        ),
    ]
