# Generated by Django 4.2 on 2023-07-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_shipmentbilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentbilling',
            name='onboard_handling_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentbilling',
            name='onboard_handling_ton',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
