# Generated by Django 3.1.11 on 2021-06-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20210601_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingtracker',
            name='amount',
            field=models.FloatField(),
        ),
    ]
