# Generated by Django 3.1.11 on 2021-06-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20210601_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingtracker',
            name='rental_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
