# Generated by Django 4.2 on 2023-08-03 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('billing', '0004_shipmentbilling_onboard_handling_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentbilling',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='shipmentbilling',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='shipmentbilling',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='shipmentbilling',
            name='onboard_handling_amount',
        ),
        migrations.RemoveField(
            model_name='shipmentbilling',
            name='onboard_handling_ton',
        ),
        migrations.RemoveField(
            model_name='shipmentbilling',
            name='tonnage',
        ),
        migrations.CreateModel(
            name='ShipmentBillingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('tonnage', models.FloatField(null=True)),
                ('onboard_handling_amount', models.FloatField(blank=True, null=True)),
                ('onboard_handling_ton', models.FloatField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
                ('shipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.shipmentbilling')),
            ],
            options={
                'unique_together': {('contractor', 'shipment')},
            },
        ),
    ]
