# Generated by Django 3.1.11 on 2021-06-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billingtracker_rental_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddon',
            name='sent_to',
            field=models.CharField(blank=True, choices=[('Sir Jun', 'Sir Jun'), ('Accounting/Advance', 'Accounting/Advance'), ('Mines', 'Mines'), ('Others', 'Others')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='billingtracker',
            name='contractor',
            field=models.CharField(choices=[('CKDI', 'CKDI'), ('TRGC', 'TRGC'), ('SDMC', 'SDMC'), ('SKAFF', 'SKAFF'), ('HPK', 'HPK'), ('NB', 'NICKELBASE')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='billingtracker',
            name='purpose',
            field=models.CharField(choices=[('SHIP', 'Shipment'), ('REN', 'Rental'), ('LIM', 'Limonite'), ('ENV', 'Envi')], max_length=32, null=True),
        ),
    ]
