# Generated by Django 3.1.11 on 2021-06-02 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20210602_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingtracker',
            name='Last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
