# Generated by Django 3.1.11 on 2021-06-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_billingtracker_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingtracker',
            name='Last_update',
        ),
        migrations.AddField(
            model_name='billingtracker',
            name='fileup',
            field=models.FileField(null=True, upload_to='./final_files'),
        ),
        migrations.AddField(
            model_name='billingtracker',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
