# Generated by Django 3.1.11 on 2021-06-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20210602_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingtracker',
            name='fileup',
            field=models.FileField(null=True, upload_to='./final_files/'),
        ),
    ]
