# Generated by Django 3.1.11 on 2021-06-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20210602_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddon',
            name='received_from',
            field=models.CharField(blank=True, choices=[('Sir Jun', 'Sir Jun'), ('Accounting/Advance', 'Accounting/Advance'), ('Mines', 'Mines'), ('Others', 'Others')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='billingtracker',
            name='fileup',
            field=models.FileField(blank=True, null=True, upload_to='./final_files/'),
        ),
    ]
