# Generated by Django 3.1.11 on 2021-06-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20210602_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingtracker',
            name='rental_type',
        ),
        migrations.AddField(
            model_name='billingtracker',
            name='specification',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
