# Generated by Django 3.1.11 on 2021-06-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_auto_20210602_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingtracker',
            name='operating_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingtracker',
            name='tonnage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
