# Generated by Django 3.1.11 on 2021-06-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_auto_20210603_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddon',
            name='received_from',
            field=models.CharField(blank=True, choices=[('Sir Jun', 'Sir Jun'), ('Accounting/Advance', 'Accounting/Advance'), ('Mines', 'Mines'), ('Envi', 'Envi'), ('Others', 'Others')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddon',
            name='sent_to',
            field=models.CharField(blank=True, choices=[('Sir Jun', 'Sir Jun'), ('Accounting/Advance', 'Accounting/Advance'), ('Mines', 'Mines'), ('Envi', 'Envi'), ('Others', 'Others')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='billingtracker',
            name='contractor',
            field=models.CharField(choices=[('CKDI', 'CKDI'), ('TRGC', 'TRGC'), ('SDMC', 'SDMC'), ('SKAFF', 'SKAFF'), ('HPK', 'HPK'), ('NB', 'NICKELBASE'), ('POL', 'POLARIS')], max_length=32, null=True),
        ),
    ]
