# Generated by Django 3.1.11 on 2021-08-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20210629_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='saveFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
