# Generated by Django 3.1.11 on 2021-08-04 03:03

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_auto_20210804_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingtracker',
            name='fileup',
            field=models.FileField(blank=True, null=True, upload_to=billing.models.filepath),
        ),
    ]
