# Generated by Django 3.1.11 on 2021-08-14 01:34

import billing.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_auto_20210804_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingtracker',
            name='contractor',
            field=models.CharField(choices=[('CKDI', 'CKDI'), ('TRGC', 'TRGC'), ('SDMC', 'SDMC'), ('SKAFF', 'SKAFF'), ('HPK', 'HPK'), ('NB', 'NICKELBASE'), ('POL', 'POLARIS'), ('ETER', 'ETER')], max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=32, null=True)),
                ('fileup', models.FileField(blank=True, null=True, upload_to=billing.models.filepath)),
                ('billing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.billingtracker')),
            ],
        ),
    ]
