# Generated by Django 3.1.11 on 2021-08-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_auto_20210814_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingtracker',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
