# Generated by Django 4.0 on 2022-03-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_alter_billingaddon_id_alter_billingtracker_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingtracker',
            name='contractor',
            field=models.CharField(choices=[('CKDI', 'CKDI'), ('TRGC', 'TRGC'), ('SDMC', 'SDMC'), ('HPK', 'HPK'), ('NB', 'NICKELBASE'), ('POL', 'POLARIS'), ('ETER', 'ETER')], max_length=32, null=True),
        ),
    ]
