# Generated by Django 5.0.6 on 2024-06-06 10:17

import django.db.models.deletion
import mine_planning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_type', models.CharField(max_length=40, null=True)),
                ('map_prefix', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MinePlanningEngineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MapDocumentControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(null=True)),
                ('material', models.CharField(blank=True, choices=[('SAP', 'Saprolite'), ('LIM', 'Limonite')], max_length=3, null=True)),
                ('ridge', models.CharField(blank=True, choices=[('', ''), ('ALL_', 'ALL Ridges'), ('CA_', 'Cagdianao'), ('HY_', 'Haya'), ('T1_', 'Taga 1'), ('T2_', 'Taga 2'), ('T3_', 'Taga 3'), ('UR_', 'Urbiz')], default='', max_length=10)),
                ('mineblock', models.CharField(blank=True, max_length=30, null=True)),
                ('year_on_map', models.CharField(max_length=4, null=True)),
                ('month', models.CharField(blank=True, choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'June'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='', max_length=9, null=True)),
                ('week_start', models.CharField(blank=True, choices=[('W1', 'Week 1'), ('W2', 'Week 2'), ('W3', 'Week 3'), ('W4', 'Week 4')], default='', max_length=2, null=True)),
                ('week_end', models.CharField(blank=True, choices=[('W1', 'Week 1'), ('W2', 'Week 2'), ('W3', 'Week 3'), ('W4', 'Week 4')], default='', max_length=2, null=True)),
                ('bench', models.CharField(blank=True, max_length=30, null=True)),
                ('number', models.CharField(blank=True, max_length=3)),
                ('revision', models.IntegerField(default=0)),
                ('revision_notes', models.TextField(blank=True, max_length=256)),
                ('map_uploads_img', models.FileField(blank=True, null=True, upload_to=mine_planning.models.filepath)),
                ('map_uploads_zip', models.FileField(blank=True, null=True, upload_to=mine_planning.models.filepath)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
                ('revised_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mine_planning.mapdocumentcontrol')),
                ('map_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mine_planning.maptype')),
                ('map_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mine_planning.mineplanningengineer')),
            ],
        ),
    ]
