# Generated by Django 4.2.7 on 2024-04-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdocumentcontrol',
            name='ridge',
            field=models.CharField(blank=True, choices=[('', ''), ('ALL_', 'ALL Ridges'), ('CA_', 'Cagdianao'), ('HY_', 'Haya'), ('T1_', 'Taga 1'), ('T2_', 'Taga 2'), ('T3_', 'Taga 3'), ('UR_', 'Urbiz')], default='', max_length=10),
        ),
    ]
