# Generated by Django 4.2.7 on 2025-01-16 06:50

from django.db import migrations, models
import mine_planning.models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdocumentcontrol',
            name='map_title',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mapdocumentcontrol',
            name='map_uploads_zip',
            field=models.FileField(blank=True, null=True, upload_to=mine_planning.models.filepath_zip),
        ),
    ]
