# Generated by Django 5.1.5 on 2025-01-23 15:31

import custom.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True)),
                ('abbreviation', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('resource_code', custom.fields.NameField(blank=True, help_text='A single letter used for equipment code assignment for SAP resources.', max_length=1, null=True, unique=True)),
                ('service', models.CharField(choices=[('Contractor', 'Contractor'), ('Operating Company', 'OpCo'), ('Government Agency', 'Govt')], max_length=30, null=True)),
                ('warehouse_code', custom.fields.NameField(blank=True, max_length=3, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('abbreviation', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True)),
                ('abbreviation', models.CharField(max_length=10, null=True)),
                ('parent_division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.division')),
            ],
        ),
        migrations.CreateModel(
            name='ManilaGpsApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('owner__name')), models.OrderBy(models.F('key'))],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('organization.organization',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True)),
                ('parent_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.department')),
            ],
        ),
    ]
