# Generated by Django 4.1.5 on 2023-02-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='service',
            field=models.CharField(choices=[('Contractor', 'Contractor'), ('Operating Company', 'OpCo'), ('Government Agency', 'Govt')], max_length=30, null=True),
        ),
    ]
