# Generated by Django 5.0.6 on 2024-06-18 15:55

import custom.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='warehouse_code',
            field=custom.fields.NameField(blank=True, max_length=3, null=True),
        ),
    ]
