# Generated by Django 4.2.7 on 2024-03-19 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManilaGpsApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=15, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('owner__name')), models.OrderBy(models.F('key'))],
            },
        ),
    ]
