# Generated by Django 4.1.7 on 2023-03-24 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('abbreviation', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('abbreviation', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('parent_division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='parent_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.division'),
        ),
    ]
