# Generated by Django 4.2.7 on 2024-03-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_manilagpsapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manilagpsapikey',
            name='key',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
