# Generated by Django 5.0.6 on 2024-06-18 16:59

import custom.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_warehouse_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='resource_code',
            field=custom.fields.NameField(blank=True, help_text='A single letter used for equipment code assignment for SAP resources.', max_length=1, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='warehouse_code',
            field=custom.fields.NameField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
