# Generated by Django 4.2.7 on 2024-04-13 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_manilagpsapikey_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('organization.organization',),
        ),
    ]
