# Generated by Django 4.1.7 on 2023-04-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_rename_parent_division_section_parent_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('abbreviation', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'organization_organizationunit',
                'managed': False,
            },
        ),
    ]
