# Generated by Django 4.2 on 2023-04-25 07:03

import custom.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': [models.OrderBy(models.F('code'))],
            },
        ),
        migrations.CreateModel(
            name='ProfitCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SapCostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('long_name', custom.fields.AlphaNumeric(blank=True, max_length=40, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('profit_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptrollership.profitcenter')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('budget', models.DecimalField(decimal_places=2, default=0, help_text='Planned prior to the fiscal year.', max_digits=13)),
                ('adjusted_budget', models.DecimalField(decimal_places=2, default=0, help_text='Approved minor revision of budget. May be updated from time to time.', max_digits=13)),
                ('forecast', models.DecimalField(decimal_places=2, default=0, help_text='Recomputed cost for the fiscal year due to major changes in operating assumptions.', max_digits=13)),
                ('actual', models.DecimalField(decimal_places=2, default=0, help_text='Actual booked cost.', max_digits=13)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptrollership.sapcostcenter')),
                ('gl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptrollership.generalledgeraccount')),
            ],
            options={
                'ordering': ['-year', '-month', 'cost_center', 'gl'],
            },
        ),
        migrations.CreateModel(
            name='CostCenterConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptrollership.costcenter')),
                ('sap_cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptrollership.sapcostcenter')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('sap_cost_center__name')), models.OrderBy(models.F('old_cost_center__name'))],
            },
        ),
        migrations.AddIndex(
            model_name='monthlycost',
            index=models.Index(fields=['year', 'month'], name='comptroller_year_fec49d_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycost',
            index=models.Index(fields=['month'], name='comptroller_month_a4d466_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlycost',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'cost_center', 'gl'), name='unique_monthly_cost'),
        ),
        migrations.AddConstraint(
            model_name='costcenterconversion',
            constraint=models.UniqueConstraint(fields=('old_cost_center', 'sap_cost_center'), name='unique_cost_center_conversion'),
        ),
    ]
