# Generated by Django 4.1.3 on 2022-11-09 06:25

import custom.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': [models.OrderBy(models.F('code'))],
            },
        ),
        migrations.CreateModel(
            name='SapCostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('long_name', custom.fields.AlphaNumeric(blank=True, max_length=40, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostCenterConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptrollership.costcenter')),
                ('sap_cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptrollership.sapcostcenter')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('sap_cost_center__name')), models.OrderBy(models.F('old_cost_center__name'))],
            },
        ),
        migrations.AddConstraint(
            model_name='costcenterconversion',
            constraint=models.UniqueConstraint(fields=('old_cost_center', 'sap_cost_center'), name='unique_cost_center_conversion'),
        ),
    ]
