# Generated by Django 5.0.6 on 2024-06-06 10:17

import custom.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Activity categories',
            },
        ),
        migrations.CreateModel(
            name='ActivityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': [models.OrderBy(models.F('code'))],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('budget', models.DecimalField(decimal_places=2, default=0, help_text='Planned prior to the fiscal year.', max_digits=13)),
                ('adjusted_budget', models.DecimalField(decimal_places=2, default=0, help_text='Approved minor revision of budget. May be updated from time to time.', max_digits=13)),
                ('forecast', models.DecimalField(decimal_places=2, default=0, help_text='Recomputed cost for the fiscal year due to major changes in operating assumptions.', max_digits=13)),
                ('actual', models.DecimalField(decimal_places=2, default=0, help_text='Actual booked cost.', max_digits=13)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'cost_center', 'gl'],
            },
        ),
        migrations.CreateModel(
            name='OperationHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfitCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SapCostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('long_name', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CostCenterConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('with_contract', models.BooleanField(default=False)),
                ('with_inhouse', models.BooleanField(default=False)),
                ('with_rental', models.BooleanField(default=False)),
                ('activity_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comptrollership.activitycategory')),
                ('activity_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comptrollership.activitycode')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('sap_cost_center__name')), models.OrderBy(models.F('old_cost_center__name'))],
            },
        ),
    ]
