# Generated by Django 4.2.7 on 2024-04-04 08:25

import custom.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('comptrollership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperationHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='costcenterconversion',
            name='equipment',
            field=models.ManyToManyField(to='fleet.equipmentclass'),
        ),
        migrations.AddField(
            model_name='costcenterconversion',
            name='operation_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costcenterconversion',
            name='rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='costcenterconversion',
            name='with_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='costcenterconversion',
            name='with_inhouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='costcenterconversion',
            name='with_rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptrollership.material'),
        ),
        migrations.AddField(
            model_name='costcenterconversion',
            name='activity_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comptrollership.activitycategory'),
        ),
        migrations.AddField(
            model_name='costcenterconversion',
            name='activity_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comptrollership.activitycode'),
        ),
        migrations.AddField(
            model_name='costcenterconversion',
            name='operation_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comptrollership.operationhead'),
        ),
    ]
