# Generated by Django 4.1.7 on 2023-04-05 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptrollership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('budget', models.DecimalField(decimal_places=2, default=0, help_text='Planned prior to the fiscal year.', max_digits=13)),
                ('adjusted_budget', models.DecimalField(decimal_places=2, default=0, help_text='Approved minor revision of budget. May be updated from time to time.', max_digits=13)),
                ('forecast', models.DecimalField(decimal_places=2, default=0, help_text='Recomputed cost for the fiscal year due to major changes in operating assumptions.', max_digits=13)),
                ('actual', models.DecimalField(decimal_places=2, default=0, help_text='Actual booked cost.', max_digits=13)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptrollership.sapcostcenter')),
                ('gl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptrollership.generalledgeraccount')),
            ],
            options={
                'ordering': ['-year', '-month', 'cost_center', 'gl'],
            },
        ),
        migrations.AddIndex(
            model_name='monthlycost',
            index=models.Index(fields=['year', 'month'], name='comptroller_year_fec49d_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycost',
            index=models.Index(fields=['month'], name='comptroller_month_a4d466_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlycost',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'cost_center', 'gl'), name='unique_monthly_cost'),
        ),
    ]
