# Generated by Django 4.0.6 on 2022-07-13 06:10

import custom.fields
from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('comptrollership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalledgeraccount',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('code'))]},
        ),
        migrations.AddField(
            model_name='sapcostcenter',
            name='long_name',
            field=custom.fields.AlphaNumeric(blank=True, max_length=40, null=True),
        ),
    ]
