# Generated by Django 5.0.6 on 2024-06-06 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptrollership', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenterconversion',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='fleet.equipmentclass'),
        ),
        migrations.AddField(
            model_name='costcenterconversion',
            name='old_cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptrollership.costcenter'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptrollership.material'),
        ),
        migrations.AddField(
            model_name='monthlycost',
            name='gl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptrollership.generalledgeraccount'),
        ),
        migrations.AddField(
            model_name='costcenterconversion',
            name='operation_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comptrollership.operationhead'),
        ),
        migrations.AddField(
            model_name='sapcostcenter',
            name='profit_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptrollership.profitcenter'),
        ),
        migrations.AddField(
            model_name='monthlycost',
            name='cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptrollership.sapcostcenter'),
        ),
        migrations.AddField(
            model_name='costcenterconversion',
            name='sap_cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptrollership.sapcostcenter'),
        ),
        migrations.AddIndex(
            model_name='monthlycost',
            index=models.Index(fields=['year', 'month'], name='comptroller_year_fec49d_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlycost',
            index=models.Index(fields=['month'], name='comptroller_month_a4d466_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlycost',
            constraint=models.CheckConstraint(check=models.Q(('year__gte', 2021)), name='monthlycost_year_min'),
        ),
        migrations.AddConstraint(
            model_name='monthlycost',
            constraint=models.CheckConstraint(check=models.Q(('month__gte', 1)), name='monthlycost_month_min'),
        ),
        migrations.AddConstraint(
            model_name='monthlycost',
            constraint=models.CheckConstraint(check=models.Q(('month__lte', 13)), name='monthlycost_month_max'),
        ),
        migrations.AddConstraint(
            model_name='monthlycost',
            constraint=models.UniqueConstraint(fields=('year', 'month', 'cost_center', 'gl'), name='unique_monthly_cost'),
        ),
        migrations.AddConstraint(
            model_name='costcenterconversion',
            constraint=models.UniqueConstraint(fields=('old_cost_center', 'sap_cost_center'), name='unique_cost_center_conversion'),
        ),
    ]
