# Generated by Django 4.2.7 on 2024-04-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('comptrollership', '0002_activitycategory_activitycode_material_operationhead_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitycategory',
            options={'verbose_name_plural': 'Activity categories'},
        ),
        migrations.RemoveField(
            model_name='costcenterconversion',
            name='rental',
        ),
        migrations.AlterField(
            model_name='costcenterconversion',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='fleet.equipmentclass'),
        ),
    ]
