# Generated by Django 2.2.5 on 2019-09-06 06:00

import custom.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', custom.fields.NameField(max_length=100)),
                ('middle_name', custom.fields.NameField(blank=True, max_length=100, null=True)),
                ('last_name', custom.fields.NameField(max_length=100)),
                ('name_suffix', custom.fields.NameField(blank=True, help_text='Junior, Senior, III, etc.', max_length=20, null=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'middle_name'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectivity', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.Designation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.Person')),
            ],
            options={
                'ordering': ['-effectivity'],
            },
        ),
    ]
