# Generated by Django 3.2 on 2021-06-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetail',
            name='interval_class',
            field=models.CharField(choices=[('preparation_loading', 'Preparation for Loading'), ('discharging_of_backload', 'Discharging of Backload'), ('lct_repair', 'LCT Repair Standby'), ('loading', 'Loading'), ('pause_loading', 'Stop Loading due to Change Shift'), ('preparation_departure', 'Preparation for Departure'), ('travel_to_vessel', 'Travel to Vessel'), ('preparation_unloading', 'Preparation for Unloading'), ('unloading', 'Unloading'), ('pause_unloading', 'Stop Unloading due to FV Crane Trouble'), ('preparation_castoff', 'Preparation for Castoff'), ('travel_to_wharf', 'Travel to Wharf'), ('waiting_for_cargo', 'Wating for Cargo'), ('waiting_for_dock', 'Waiting for Available Dock'), ('waiting_for_tide', 'Waiting for Safe Water Level'), ('waiting_for_vessel', 'Waiting for Vessel'), ('waiting_for_shipside_position', 'Waiting for Available Shipside Position'), ('sun_drying', 'Sun Drying'), ('swell', 'Swell'), ('rain', 'Rain'), ('rain_swell', 'Rain and Swell'), ('refueling', 'Refueling'), ('rewatering', 'Rewatering'), ('end', 'End')], max_length=30),
        ),
    ]
