# Generated by Django 3.1 on 2020-08-16 03:08

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laydaysstatement',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('completed_loading'), descending=True, nulls_last=False), django.db.models.expressions.OrderBy(django.db.models.expressions.F('nor_accepted'), descending=True, nulls_last=False), django.db.models.expressions.OrderBy(django.db.models.expressions.F('nor_tender'), descending=True, nulls_last=False), django.db.models.expressions.OrderBy(django.db.models.expressions.F('arrival_tmc'), descending=True, nulls_last=False), django.db.models.expressions.OrderBy(django.db.models.expressions.F('arrival_pilot'), descending=True, nulls_last=False)]},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('laydaysstatement__completed_loading'), descending=True, nulls_last=False), django.db.models.expressions.OrderBy(django.db.models.expressions.F('laydaysstatement__nor_accepted'), descending=True, nulls_last=False), django.db.models.expressions.OrderBy(django.db.models.expressions.F('laydaysstatement__nor_tender'), descending=True, nulls_last=False), django.db.models.expressions.OrderBy(django.db.models.expressions.F('laydaysstatement__arrival_tmc'), descending=True, nulls_last=False), django.db.models.expressions.OrderBy(django.db.models.expressions.F('laydaysstatement__arrival_pilot'), descending=True, nulls_last=False), django.db.models.expressions.OrderBy(django.db.models.expressions.F('name'), descending=True)]},
        ),
    ]
