# Generated by Django 3.0 on 2020-01-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laydaysstatement',
            name='can_test_factor',
            field=models.DecimalField(choices=[(1, '1.0'), (0.5, '0.5'), (0, '0.0')], decimal_places=1, default=0.5, help_text='The number of can tests times this factor times 5 minutes will be deducted to laytime consumed.', max_digits=2),
        ),
    ]
