# Generated by Django 4.0.6 on 2022-09-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedlaydaysstatement',
            name='signed_statement',
            field=models.FileField(blank=True, null=True, upload_to='laydays/'),
        ),
    ]
