# Generated by Django 3.1 on 2020-08-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laydaysdetail',
            name='laytime_rate',
            field=models.PositiveSmallIntegerField(choices=[(100, '100'), (80, '80'), (75, '75'), (50, '50'), (25, '25'), (0, '0')]),
        ),
    ]
