# Generated by Django 4.2 on 2023-06-15 04:16

import custom.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laydaysstatement',
            name='vessel_voyage',
            field=custom.fields.AlphaNumeric(blank=True, max_length=8, null=True),
        ),
    ]
