# Generated by Django 3.0.7 on 2020-07-29 02:48

import custom.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='laydaysstatement',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('completed_loading'), descending=True, nulls_last=False), django.db.models.expressions.OrderBy(django.db.models.expressions.F('arrival_tmc'), descending=True, nulls_last=False)]},
        ),
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('laydaysstatement__completed_loading'), descending=True, nulls_last=False), django.db.models.expressions.OrderBy(django.db.models.expressions.F('laydaysstatement__arrival_tmc'), descending=True, nulls_last=False)]},
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='end_loading',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='start_loading',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='tonnage',
        ),
        migrations.AddField(
            model_name='shipment',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='US$', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='boulders_freight_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='US$', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='boulders_processing_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='US$', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='boulders_tonnage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='demurrage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='despatch',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='final_fe',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Fe'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='final_moisture',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%H₂O'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='final_ni',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Ni'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='US$', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='spec_fe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='%Fe Spec'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='spec_moisture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='%H₂O Spec'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='spec_ni',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='%Ni Spec'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='spec_tonnage',
            field=models.PositiveIntegerField(blank=True, help_text='Tonnage in sales contract.', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='target_tonnage',
            field=models.PositiveIntegerField(blank=True, help_text='Determined during initial draft survey.', null=True),
        ),
        migrations.AlterField(
            model_name='laydaysstatement',
            name='can_test_factor',
            field=models.DecimalField(choices=[(1, '1.0'), (0.5, '0.5'), (0, '0.0')], decimal_places=1, default=0.5, help_text='The number of can tests times this factor times 5 minutes\n            will be deducted to laytime consumed.', max_digits=2),
        ),
        migrations.AddField(
            model_name='shipment',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipment.Buyer'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipment.Destination'),
        ),
    ]
