# Generated by Django 3.0.7 on 2020-08-02 06:47

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedLayDaysStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('statement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shipment.LayDaysStatement')),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('statement__completed_loading'), descending=True, nulls_last=False), django.db.models.expressions.OrderBy(django.db.models.expressions.F('statement__arrival_tmc'), descending=True, nulls_last=False)],
            },
        ),
    ]
