# Generated by Django 4.2 on 2023-12-22 07:53

from django.db import migrations, models
import django.db.models.deletion
import shipment.functions


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to=shipment.functions.filepath_shipmentvideo)),
                ('images_in_pdf', models.FileField(blank=True, null=True, upload_to=shipment.functions.filepath_shipmentimages)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment')),
            ],
        ),
    ]
