# Generated by Django 5.1.5 on 2025-12-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_alter_laydaysstatement_tonnage'),
    ]

    operations = [
        migrations.AddField(
            model_name='laydaysstatement',
            name='negotiated_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Negotiated allowable lay days.'),
        ),
    ]
