# Generated by Django 3.1.1 on 2020-09-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_auto_20200825_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='laydaysstatement',
            name='negotiated',
            field=models.BooleanField(default=False, help_text='Demurrage/Despatch is negotiated.'),
        ),
        migrations.AddField(
            model_name='laydaysstatement',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
