# Generated by Django 4.2.7 on 2024-05-20 02:20

from django.db import migrations, models
import shipment.functions


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_draftsurvey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draftsurvey',
            options={'ordering': [models.OrderBy(models.F('shipment__laydaysstatement__completed_loading'), descending=True, nulls_last=False), models.OrderBy(models.F('shipment__laydaysstatement__nor_accepted'), descending=True, nulls_last=False), models.OrderBy(models.F('shipment__laydaysstatement__nor_tender'), descending=True, nulls_last=False), models.OrderBy(models.F('shipment__laydaysstatement__arrival_tmc'), descending=True, nulls_last=False), models.OrderBy(models.F('shipment__laydaysstatement__arrival_pilot'), descending=True, nulls_last=False), models.OrderBy(models.F('shipment__name'), descending=True)]},
        ),
        migrations.AddField(
            model_name='draftsurvey',
            name='mgb_receipt',
            field=models.FileField(blank=True, null=True, upload_to=shipment.functions.filepath_shipment_draftsurvey_receipt),
        ),
    ]
