# Generated by Django 3.0.7 on 2020-08-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_finalshipmentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laydaysstatement',
            name='can_test_factor',
            field=models.DecimalField(choices=[(0.0, '0.0'), (0.5, '0.5'), (1.0, '1.0')], decimal_places=1, default=0.5, help_text='The number of can tests times this factor times 5 minutes\n            will be deducted to laytime consumed.', max_digits=2),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shipment.Destination'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shipment.Vessel'),
        ),
    ]
