# Generated by Django 3.0.2 on 2020-01-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_laydaysstatement_can_test_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laydaysdetail',
            name='interval_class',
            field=models.CharField(choices=[('continuous loading', 'Continuous Loading'), ('sun drying', 'Sun Drying'), ('heavy swell', 'Heavy Swell'), ('rain', 'Rain'), ('rain and heavy swell', 'Rain and Heavy Swell'), ('waiting for cargo', 'Waiting for Cargo'), ('waiting for cargo due to rejection', 'Waiting for Cargo (rejected)'), ('waiting for loading commencement', 'Waiting for Loading Commencement'), ('end', 'End'), ('vessel arrived behind of schedule', 'Vessel Arrived Behind of Schedule'), ('others', '-')], max_length=50),
        ),
    ]
