# Generated by Django 3.2 on 2021-06-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_alter_tripdetail_interval_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laydaysstatement',
            name='demurrage_rate',
            field=models.PositiveIntegerField(default=11000, help_text='US Dollar per day'),
        ),
        migrations.AlterField(
            model_name='laydaysstatement',
            name='despatch_rate',
            field=models.PositiveIntegerField(default=5500, help_text='US Dollar per day'),
        ),
    ]
