# Generated by Django 3.1.1 on 2020-09-11 07:06

import custom.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_auto_20200907_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='laydaysstatement',
            name='laytime_terms',
            field=custom.fields.NameField(blank=True, max_length=20, null=True),
        ),
    ]
