# Generated by Django 3.0.7 on 2020-07-30 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_auto_20200730_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='dump_truck_trips',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipment.Vessel'),
        ),
    ]
