# Generated by Django 3.0.7 on 2020-08-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_auto_20200808_1507'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='laydaysdetail',
            constraint=models.UniqueConstraint(condition=models.Q(interval_class='end'), fields=('laydays', 'interval_class'), name='unique_end_laydaysdetail'),
        ),
        migrations.AddConstraint(
            model_name='tripdetail',
            constraint=models.UniqueConstraint(condition=models.Q(interval_class='end'), fields=('trip', 'interval_class'), name='unique_end_tripdetail'),
        ),
    ]
