# Generated by Django 5.1.5 on 2026-02-27 00:01

import custom.fields
import django.core.validators
import django.db.models.expressions
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_laydaysstatement_negotiated_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChromiteSale',
            fields=[
                ('shipment', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('provisional_invoice', custom.fields.SpaceLess(max_length=40)),
                ('provisional_invoice_date', models.DateField(blank=True, null=True)),
                ('provisional_wmt', models.DecimalField(decimal_places=3, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('5000'))])),
                ('provisional_moisture', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MaxValueValidator(Decimal('10')), django.core.validators.MinValueValidator(Decimal('2'))], verbose_name='%H₂O')),
                ('provisional_dmt', models.FloatField(blank=True)),
                ('provisional_chromite_content', models.DecimalField(decimal_places=4, max_digits=6, validators=[django.core.validators.MaxValueValidator(Decimal('60')), django.core.validators.MinValueValidator(Decimal('30'))], verbose_name='%Chromite')),
                ('provisional_usd_per_dmt', models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('100'))], verbose_name='$US/dmt')),
                ('provisional_invoice_rate', models.DecimalField(decimal_places=2, default=93, help_text='Percentage of billed for provisional invoice.', max_digits=5, validators=[django.core.validators.MaxValueValidator(Decimal('100')), django.core.validators.MinValueValidator(Decimal('80'))])),
                ('tmc_share', models.DecimalField(decimal_places=2, default=4, help_text='Revenue share of TMC in percentage.', max_digits=5, validators=[django.core.validators.MaxValueValidator(Decimal('40')), django.core.validators.MinValueValidator(Decimal('2'))])),
                ('provisional_shipment_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('provisional_revenue_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('provisional_revenue_php', models.FloatField(blank=True)),
                ('bill_of_lading_date', models.DateField()),
                ('usd_to_php', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('30'))])),
                ('final_invoice', custom.fields.SpaceLess(blank=True, max_length=40, null=True)),
                ('final_invoice_date', models.DateField(blank=True, null=True)),
                ('final_wmt', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('5000'))])),
                ('final_moisture', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('10')), django.core.validators.MinValueValidator(Decimal('2'))], verbose_name='%H₂O')),
                ('final_dmt', models.FloatField(blank=True, null=True)),
                ('final_chromite_content', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('60')), django.core.validators.MinValueValidator(Decimal('30'))], verbose_name='%Chromite')),
                ('final_usd_per_dmt', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('100'))], verbose_name='$US/dmt')),
                ('final_shipment_price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='93% of total amount', max_digits=10, null=True)),
                ('final_revenue_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('final_revenue_php', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScandiumSale',
            fields=[
                ('shipment', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField()),
                ('bill_of_lading_date', models.DateField(blank=True, null=True)),
                ('precipitate_wet_kg', models.DecimalField(decimal_places=2, help_text='Scandium Oxalate Precipitate sold by THPAL in wet kg', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('precipitate_dry_kg', models.DecimalField(decimal_places=2, help_text='Scandium Oxalate Precipitate sold by THPAL in dry kg', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('100'))])),
                ('scandium_oxalate_percentage', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MaxValueValidator(Decimal('40')), django.core.validators.MinValueValidator(Decimal('10'))], verbose_name='%Scandium Oxalate')),
                ('scandium_oxalate_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('scandium_oxide_kg', models.DecimalField(decimal_places=1, max_digits=6)),
                ('usd_per_kg_scandium_oxide', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('scandium_oxide_kg__gt', django.db.models.expressions.CombinedExpression(models.F('scandium_oxalate_kg'), '*', models.Value(1.52)))), name='min_scandium_oxide'), models.CheckConstraint(condition=models.Q(('scandium_oxide_kg__lt', django.db.models.expressions.CombinedExpression(models.F('scandium_oxalate_kg'), '*', models.Value(1.54)))), name='max_scandium_oxide')],
            },
        ),
        migrations.CreateModel(
            name='THPALFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')])),
                ('wmt_oversize', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('wmt_undersize', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('dmt_undersize', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ni_ton', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('co_ton', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('certificate', models.FileField(blank=True, null=True, upload_to='assay/hpal_feed/')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('year'), descending=True), models.OrderBy(models.F('month'), descending=True)],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='unique_year_month')],
            },
        ),
    ]
