# Generated by Django 3.1.1 on 2020-09-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_laydaysstatement_laytime_terms'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('interval_from', 'interval_to'), name='unique_lct_trip_interval'),
        ),
    ]
