# Generated by Django 3.0.7 on 2020-07-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_auto_20200730_1055'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(check=models.Q(('demurrage', 0), ('despatch', 0), _connector='OR'), name='dem_des_with_zero'),
        ),
    ]
