# Generated by Django 5.1.5 on 2026-02-27 01:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_chromitesale_scandiumsale_thpalfeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thpalfeed',
            name='wmt_oversize',
        ),
        migrations.RemoveField(
            model_name='thpalfeed',
            name='wmt_undersize',
        ),
        migrations.AddField(
            model_name='thpalfeed',
            name='fe_ton',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='thpalfeed',
            name='percent_moisture',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='thpalfeed',
            name='wmt_oversize_h',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hauled overzise in a month', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='thpalfeed',
            name='wmt_oversize_s',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Month-end inventory of versize ore', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='thpalfeed',
            name='wmt_slurry_feed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='thpalfeed',
            name='co_ton',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='thpalfeed',
            name='ni_ton',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
