# Generated by Django 5.1.5 on 2026-02-27 03:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_remove_thpalfeed_wmt_oversize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thpalfeed',
            name='co_ton',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='thpalfeed',
            name='dmt_undersize',
            field=models.DecimalField(decimal_places=3, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='thpalfeed',
            name='fe_ton',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='thpalfeed',
            name='ni_ton',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='thpalfeed',
            name='percent_moisture',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
