# Generated by Django 5.1.5 on 2026-03-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_remove_thpalfeed_wmt_oversize_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thpalfeed',
            options={'ordering': [models.OrderBy(models.F('year'), descending=True), models.OrderBy(models.F('month'), descending=True)], 'verbose_name': 'THPAL Feed', 'verbose_name_plural': 'THPAL Feed'},
        ),
    ]
