# Generated by Django 5.1.5 on 2026-02-28 00:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0006_alter_thpalfeed_co_ton_alter_thpalfeed_dmt_undersize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thpalfeed',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
