# Generated by Django 5.0.6 on 2024-06-06 10:17

import custom.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('LH', 'Legal Holiday'), ('NH', 'Negotiated Holiday'), ('SH', 'Special Holiday')], max_length=2)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='local_calendar.holidayevent')),
            ],
            options={
                'ordering': ['date', 'event'],
            },
        ),
    ]
