# Generated by Django 4.0.4 on 2022-04-21 10:43

import custom.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Equipment Class',
                'verbose_name_plural': 'Equipment Classes',
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='EquipmentManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='TrackedExcavator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_number', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['fleet_number'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('equipment_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipmentclass')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipmentmanufacturer')),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('manufacturer__name')), django.db.models.expressions.OrderBy(django.db.models.expressions.F('equipment_class__name')), django.db.models.expressions.OrderBy(django.db.models.expressions.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_number', models.PositiveSmallIntegerField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost in Philippine Peso', max_digits=12)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('date_phased_out', models.DateField(blank=True, null=True)),
                ('serial_number', custom.fields.NameField(blank=True, max_length=100, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipmentmodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('owner__name')), django.db.models.expressions.OrderBy(django.db.models.expressions.F('model__equipment_class__name')), django.db.models.expressions.OrderBy(django.db.models.expressions.F('fleet_number'))],
            },
        ),
    ]
