# Generated by Django 5.0.6 on 2024-06-06 10:17

import custom.fields
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='ChassisSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.AlphaNumeric(max_length=100, unique=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='EngineSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.AlphaNumeric(max_length=100, unique=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='EquipmentManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='PlateNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', custom.fields.AlphaNumeric(max_length=10, unique=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('plate_number'))],
            },
        ),
        migrations.CreateModel(
            name='TrackedExcavator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fleet_number', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'ordering': ['fleet_number'],
            },
        ),
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom.unitofmeasure')),
            ],
            options={
                'verbose_name_plural': 'Capacities',
                'ordering': [models.OrderBy(models.F('unit_of_measure__name')), models.OrderBy(models.F('value'))],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost in Philippine Peso', max_digits=12)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('date_phased_out', models.DateField(blank=True, null=True)),
                ('date_disposal', models.DateField(blank=True, null=True)),
                ('asset_tag_id', custom.fields.NameField(blank=True, max_length=20, null=True)),
                ('asset_serial_number', custom.fields.NameField(blank=True, max_length=20, null=True)),
                ('asset_code', custom.fields.NameField(blank=True, help_text='SAP ID', max_length=20, null=True)),
                ('service_life', models.PositiveSmallIntegerField(blank=True, help_text='No. of months', null=True)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('fleet_number', models.PositiveSmallIntegerField()),
                ('year_model', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('certificate_of_registration_no', models.CharField(blank=True, max_length=30, null=True)),
                ('cr_date', models.DateField(blank=True, null=True)),
                ('mv_file_no', models.CharField(blank=True, max_length=30, null=True)),
                ('engine_serial_number', custom.fields.AlphaNumeric(blank=True, max_length=100, null=True)),
                ('plate_number', custom.fields.NameField(blank=True, max_length=20, null=True)),
                ('month_of_registration', models.CharField(blank=True, choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], help_text='Based on plate number', max_length=20, null=True)),
                ('chassis_serial_number', custom.fields.NameField(blank=True, max_length=100, null=True)),
                ('body_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.bodytype')),
                ('department_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organizationunit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': [models.OrderBy(models.F('owner__name')), models.OrderBy(models.F('equipment_class__name')), models.OrderBy(models.F('fleet_number'))],
            },
        ),
        migrations.CreateModel(
            name='AdditionalEquipmentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost in Philippine Peso', max_digits=12)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('date_phased_out', models.DateField(blank=True, null=True)),
                ('date_disposal', models.DateField(blank=True, null=True)),
                ('asset_tag_id', custom.fields.NameField(blank=True, max_length=20, null=True)),
                ('asset_serial_number', custom.fields.NameField(blank=True, max_length=20, null=True)),
                ('asset_code', custom.fields.NameField(blank=True, help_text='SAP ID', max_length=20, null=True)),
                ('service_life', models.PositiveSmallIntegerField(blank=True, help_text='No. of months', null=True)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderEquipment',
            fields=[
            ],
            options={
                'verbose_name_plural': 'provider equipment units',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fleet.equipment',),
        ),
        migrations.CreateModel(
            name='EquipmentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Equipment Class',
                'verbose_name_plural': 'Equipment Classes',
                'ordering': [models.OrderBy(models.F('name'))],
                'indexes': [models.Index(fields=['name'], name='fleet_equip_name_abc154_idx')],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.equipmentclass'),
        ),
        migrations.CreateModel(
            name='EquipmentIdlingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('idling', models.BooleanField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentIgnitionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('ignition', models.BooleanField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipment')),
            ],
            options={
                'verbose_name_plural': 'equipment ignition statuses',
            },
        ),
        migrations.CreateModel(
            name='EquipmentMobileNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('spaceless_number', custom.fields.SpaceLess(blank=True, max_length=20, null=True, unique=True)),
                ('equipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.equipment')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('equipment__owner__name')), models.OrderBy(models.F('equipment__equipment_class__name')), models.OrderBy(models.F('equipment__fleet_number'))],
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', custom.fields.NameField(max_length=40)),
                ('equipment_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipmentclass')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipmentmanufacturer')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('manufacturer__name')), models.OrderBy(models.F('equipment_class__name')), models.OrderBy(models.F('name'))],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipmentmodel'),
        ),
        migrations.CreateModel(
            name='ProviderEquipmentRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_condition', models.BooleanField(choices=[(True, 'Used'), (False, 'New')], default=True)),
                ('delivery_year', models.PositiveSmallIntegerField()),
                ('pull_out_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField()),
                ('safety_inspection_id', models.PositiveSmallIntegerField()),
                ('sap_registered', models.BooleanField(default=False)),
                ('warehouse_registered', models.BooleanField(default=False)),
                ('year', models.PositiveSmallIntegerField(default=2010)),
                ('x_equipment_class', models.CharField(blank=True, max_length=40, null=True)),
                ('x_contractor', models.CharField(blank=True, max_length=40, null=True)),
                ('capacity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.capacity')),
                ('chassis_serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.chassisserialnumber')),
                ('engine_serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.engineserialnumber')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipmentmodel')),
                ('plate_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.platenumber')),
            ],
            options={
                'verbose_name_plural': 'provider equipment registry',
                'ordering': [models.OrderBy(models.F('year'), descending=True), models.OrderBy(models.F('equipment__owner__name')), models.OrderBy(models.F('equipment__equipment_class__name')), models.OrderBy(models.F('equipment__fleet_number'))],
            },
        ),
        migrations.AddConstraint(
            model_name='capacity',
            constraint=models.UniqueConstraint(fields=('unit_of_measure', 'value'), name='unique_equipment_capacity'),
        ),
        migrations.AddField(
            model_name='providerequipmentregistry',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.providerequipment'),
        ),
        migrations.AddIndex(
            model_name='equipmentidlingtime',
            index=models.Index(fields=['time_stamp'], name='fleet_equip_time_st_d2466a_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentidlingtime',
            index=models.Index(fields=['idling'], name='fleet_equip_idling_3c1beb_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentidlingtime',
            constraint=models.UniqueConstraint(fields=('equipment', 'time_stamp'), name='unique_equipment_idling_timestamp'),
        ),
        migrations.AddIndex(
            model_name='equipmentignitionstatus',
            index=models.Index(fields=['time_stamp'], name='fleet_equip_time_st_cdf1bd_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentignitionstatus',
            index=models.Index(fields=['ignition'], name='fleet_equip_ignitio_f250aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentignitionstatus',
            constraint=models.UniqueConstraint(fields=('equipment', 'time_stamp'), name='unique_equipment_ignition_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='equipmentmodel',
            constraint=models.UniqueConstraint(fields=('name', 'equipment_class', 'manufacturer'), name='unique_equipment_model_constraint'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('fleet_number', 'equipment_class', 'owner'), name='unique_equipment_constraint'),
        ),
        migrations.AddConstraint(
            model_name='providerequipmentregistry',
            constraint=models.CheckConstraint(check=models.Q(('delivery_year__gt', 2010)), name='contractor_registry_min_year'),
        ),
        migrations.AddConstraint(
            model_name='providerequipmentregistry',
            constraint=models.CheckConstraint(check=models.Q(('delivery_year__lt', 2050)), name='contractor_registry_max_year'),
        ),
        migrations.AddConstraint(
            model_name='providerequipmentregistry',
            constraint=models.UniqueConstraint(fields=('safety_inspection_id', 'year'), name='unique_safety_inspection_id'),
        ),
    ]
