# Generated by Django 5.1.5 on 2025-02-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['fleet_number'], name='fleet_equip_fleet_n_03f77a_idx'),
        ),
    ]
