# Generated by Django 4.1.7 on 2023-04-20 09:19

import custom.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('name'))],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='certificate_of_registration_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='cr_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='department_assigned',
            field=models.CharField(blank=True, choices=[], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='month_of_registration',
            field=models.CharField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], help_text='Based on plate number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='mv_file_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='year_model',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='body_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.bodytype'),
        ),
    ]
