# Generated by Django 4.2.7 on 2024-04-12 06:24

import custom.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_unitofmeasure'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom.unitofmeasure')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('unit_of_measure__name')), models.OrderBy(models.F('value'))],
            },
        ),
        migrations.CreateModel(
            name='ChassisSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.AlphaNumeric(max_length=100)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='EngineSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.AlphaNumeric(max_length=100)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='PlateNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', custom.fields.AlphaNumeric(max_length=10)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='ProviderEquipment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fleet.equipment',),
        ),
        migrations.CreateModel(
            name='ProviderEquipmentRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_condition', models.BooleanField(choices=[(True, 'Used'), (False, 'New')], default=True)),
                ('delivery_year', models.PositiveSmallIntegerField()),
                ('pull_out_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateField()),
                ('safety_inspection_id', models.PositiveSmallIntegerField()),
                ('sap_registered', models.BooleanField(default=False)),
                ('warehouse_registered', models.BooleanField(default=False)),
                ('year', models.PositiveSmallIntegerField(default=2010)),
                ('capacity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.capacity')),
                ('chassis_serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.chassisserialnumber')),
                ('engine_serial_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.engineserialnumber')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.providerequipment')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipmentmodel')),
                ('plate_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.platenumber')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('year'), descending=True), models.OrderBy(models.F('equipment__owner__name')), models.OrderBy(models.F('equipment__class__name')), models.OrderBy(models.F('equipment__fleet_number'))],
            },
        ),
        migrations.AddConstraint(
            model_name='providerequipmentregistry',
            constraint=models.CheckConstraint(check=models.Q(('delivery_year__gt', 2010)), name='contractor_registry_min_year'),
        ),
        migrations.AddConstraint(
            model_name='providerequipmentregistry',
            constraint=models.CheckConstraint(check=models.Q(('delivery_year__lt', 2050)), name='contractor_registry_max_year'),
        ),
        migrations.AddConstraint(
            model_name='providerequipmentregistry',
            constraint=models.UniqueConstraint(fields=('safety_inspection_id', 'year'), name='unique_safety_inspection_id'),
        ),
    ]
