# Generated by Django 4.0.4 on 2022-04-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('fleet_number', 'model', 'owner'), name='unique_equipment_constraint'),
        ),
    ]
