# Generated by Django 4.1.5 on 2023-03-07 07:07

import custom.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='serial_number',
            new_name='engine_serial_number',
        ),
        migrations.AddField(
            model_name='equipment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='chassis_serial_number',
            field=custom.fields.NameField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='plate_number',
            field=custom.fields.NameField(blank=True, max_length=20, null=True),
        ),
    ]
