# Generated by Django 4.0.4 on 2022-05-02 01:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_equipment_unique_equipment_constraint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('owner__name')), django.db.models.expressions.OrderBy(django.db.models.expressions.F('equipment_class__name')), django.db.models.expressions.OrderBy(django.db.models.expressions.F('fleet_number'))], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.RemoveConstraint(
            model_name='equipment',
            name='unique_equipment_constraint',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.equipmentclass'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('fleet_number', 'equipment_class', 'owner'), name='unique_equipment_constraint'),
        ),
    ]
