# Generated by Django 4.1.5 on 2023-03-08 02:15

import custom.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_rename_serial_number_equipment_engine_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='asset_code',
            field=custom.fields.NameField(blank=True, help_text='SAP ID', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='asset_serial_number',
            field=custom.fields.NameField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='asset_tag_id',
            field=custom.fields.NameField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='service_life',
            field=models.PositiveSmallIntegerField(blank=True, help_text='No. of months', null=True),
        ),
    ]
