# Generated by Django 4.2.7 on 2024-04-12 05:18

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_capacity_chassisserialnumber_engineserialnumber_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='providerequipmentregistry',
            name='unique_safety_inspection_id',
        ),
        migrations.AddConstraint(
            model_name='providerequipmentregistry',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Concat('registration_date__year', 'safety_inspection_id'), name='unique_safety_inspection_id'),
        ),
    ]
