# Generated by Django 5.0.6 on 2024-06-18 16:59

import custom.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_equipmentclass_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentclass',
            name='code',
            field=custom.fields.NameField(blank=True, help_text='A single letter used for equipment code assignment for SAP resources.', max_length=1, null=True, unique=True),
        ),
    ]
