# Generated by Django 4.1.7 on 2023-04-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_bodytype_equipment_certificate_of_registration_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='acquisition_cost_from_accounting',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='acquisition_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost in Philippine Peso', max_digits=12),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='department_assigned',
            field=models.CharField(blank=True, choices=[('Administrative Division', 'Administrative Division'), ('Mine Division', 'Mine Division'), ('Technical Services Division', 'Technical Services Division'), ('Mine Engineering', 'Mine Engineering'), ('Mine Operations', 'Mine Operations'), ('NA', 'NA'), ('Data Management', 'Data Management'), ('Grade Control', 'Grade Control'), ('Mine Planning', 'Mine Planning'), ('Survey', 'Survey'), ('TASS (Transportation)', 'TASS (Transportation)')], max_length=30, null=True),
        ),
    ]
