# Generated by Django 5.1.5 on 2025-02-26 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_equipment_fleet_equip_fleet_n_03f77a_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerequipmentregistry',
            name='delivery_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='providerequipmentregistry',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.equipmentmodel'),
        ),
    ]
