# Generated by Django 4.2.7 on 2024-04-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_capacity_chassisserialnumber_engineserialnumber_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacity',
            options={'ordering': [models.OrderBy(models.F('unit_of_measure__name')), models.OrderBy(models.F('value'))], 'verbose_name_plural': 'Capacities'},
        ),
        migrations.AlterModelOptions(
            name='providerequipment',
            options={'verbose_name_plural': 'provider equipment units'},
        ),
        migrations.AlterModelOptions(
            name='providerequipmentregistry',
            options={'ordering': [models.OrderBy(models.F('year'), descending=True), models.OrderBy(models.F('equipment__owner__name')), models.OrderBy(models.F('equipment__class__name')), models.OrderBy(models.F('equipment__fleet_number'))], 'verbose_name_plural': 'provider equipment registry'},
        ),
    ]
