# Generated by Django 4.2.7 on 2024-04-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_capacity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platenumber',
            options={'ordering': [models.OrderBy(models.F('plate_number'))]},
        ),
        migrations.AlterModelOptions(
            name='providerequipmentregistry',
            options={'ordering': [models.OrderBy(models.F('year'), descending=True), models.OrderBy(models.F('equipment__owner__name')), models.OrderBy(models.F('equipment__equipment_class__name')), models.OrderBy(models.F('equipment__fleet_number'))], 'verbose_name_plural': 'provider equipment registry'},
        ),
    ]
