# Generated by Django 4.2 on 2023-07-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_equipmentignitionstatus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentignitionstatus',
            options={'verbose_name_plural': 'equipment ignition statuses'},
        ),
    ]
