# Generated by Django 4.1.7 on 2023-04-24 06:47

import custom.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_remove_equipment_acquisition_cost_from_accounting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEquipmentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, help_text='Cost in Philippine Peso', max_digits=12)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('date_phased_out', models.DateField(blank=True, null=True)),
                ('date_disposal', models.DateField(blank=True, null=True)),
                ('asset_tag_id', custom.fields.NameField(blank=True, max_length=20, null=True)),
                ('asset_serial_number', custom.fields.NameField(blank=True, max_length=20, null=True)),
                ('asset_code', custom.fields.NameField(blank=True, help_text='SAP ID', max_length=20, null=True)),
                ('service_life', models.PositiveSmallIntegerField(blank=True, help_text='No. of months', null=True)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
