# Generated by Django 5.1.5 on 2025-07-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_providerequipmentregistry_delivery_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerequipmentregistry',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
