# Generated by Django 4.0.4 on 2022-05-04 06:08

import custom.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='acquisition_cost_from_accounting',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost in Philippine Peso', max_digits=12),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='acquisition_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost in Philippine Peso as recorded by TSD', max_digits=12),
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='name',
            field=custom.fields.NameField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='equipmentmodel',
            constraint=models.UniqueConstraint(fields=('name', 'equipment_class', 'manufacturer'), name='unique_equipment_model_constraint'),
        ),
    ]
