# Generated by Django 4.0 on 2022-04-20 05:44

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentclass',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('name'))]},
        ),
        migrations.AlterModelOptions(
            name='equipmentmanufacturer',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('name'))]},
        ),
        migrations.AlterModelOptions(
            name='equipmentmodel',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('manufacturer__name')), django.db.models.expressions.OrderBy(django.db.models.expressions.F('equipment_class__name')), django.db.models.expressions.OrderBy(django.db.models.expressions.F('name'))]},
        ),
    ]
