# Generated by Django 4.2.7 on 2024-04-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_remove_providerequipmentregistry_unique_safety_inspection_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providerequipmentregistry',
            options={'ordering': [models.OrderBy(models.F('year'), descending=True), models.OrderBy(models.F('equipment__owner__name')), models.OrderBy(models.F('equipment__class__name')), models.OrderBy(models.F('equipment__fleet_number'))]},
        ),
        migrations.RemoveConstraint(
            model_name='providerequipmentregistry',
            name='unique_safety_inspection_id',
        ),
        migrations.AddField(
            model_name='providerequipmentregistry',
            name='year',
            field=models.PositiveSmallIntegerField(default=2010),
        ),
        migrations.AddConstraint(
            model_name='providerequipmentregistry',
            constraint=models.UniqueConstraint(fields=('safety_inspection_id', 'year'), name='unique_safety_inspection_id'),
        ),
    ]
