# Generated by Django 4.1.5 on 2023-03-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_equipment_asset_code_equipment_asset_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
