# Generated by Django 5.0.6 on 2024-06-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_alter_equipmentclass_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerequipmentregistry',
            name='omt_registered',
            field=models.BooleanField(default=False),
        ),
    ]
