# Generated by Django 4.1.7 on 2023-04-25 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizationunit'),
        ('fleet', '0004_additionalequipmentcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='department_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organizationunit'),
        ),
    ]
