# Generated by Django 4.2.7 on 2024-04-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_platenumber_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerequipmentregistry',
            name='x_contractor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='providerequipmentregistry',
            name='x_equipment_class',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
