# Generated by Django 4.0 on 2022-04-20 05:52

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_equipmentclass_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('owner__name')), django.db.models.expressions.OrderBy(django.db.models.expressions.F('model__equipment_class__name')), django.db.models.expressions.OrderBy(django.db.models.expressions.F('fleet_number'))], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.AlterModelOptions(
            name='equipmentclass',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('name'))], 'verbose_name': 'Equipment Class', 'verbose_name_plural': 'Equipment Classes'},
        ),
    ]
