# Generated by Django 5.1.5 on 2025-07-26 05:51

import custom.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_providerequipmentregistry_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Breakdown statuses',
                'ordering': [models.OrderBy(models.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='CauseCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='ComponentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='DamageCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='PartGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('name'))],
            },
        ),
        migrations.CreateModel(
            name='EquipmentBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakdown_end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('maintenance_order', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('mo_created_on', models.DateTimeField(blank=True, null=True)),
                ('reported_on', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipment')),
                ('mo_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_order', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_breakdown_release', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_breakdown_report', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.breakdownstatus')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentBreakdownReport',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fleet.equipmentbreakdown',),
        ),
        migrations.CreateModel(
            name='MaintenanceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('operation_start', models.DateTimeField(blank=True, null=True)),
                ('operation_end', models.DateTimeField(blank=True, null=True)),
                ('cause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.causecode')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.componentcode')),
                ('damage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.damagecode')),
                ('maintenance_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipmentbreakdown')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('part_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.partgroup')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_made', models.TextField(blank=True, null=True)),
                ('task_end', models.DateTimeField(blank=True, null=True)),
                ('task_start', models.DateTimeField(blank=True, null=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.maintenanceoperation')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTaskManpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manpower_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.maintenancetask')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.workcenter')),
            ],
        ),
    ]
