# Generated by Django 4.1.7 on 2023-04-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_additionalequipmentcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='department_assigned',
            field=models.CharField(blank=True, choices=[('Administration Department', 'Administration Department'), ('Mines Division', 'Mines Division'), ('Mine Engineering', 'Mine Engineering'), ('Mine Planning', 'Mine Planning'), ('TASS (Transportation)', 'TASS (Transportation)'), ('Survey', 'Survey')], max_length=30, null=True),
        ),
    ]
