# Generated by Django 5.0.6 on 2024-06-20 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_providerequipmentregistry_omt_registered'),
        ('organization', '0003_organization_resource_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderEquipmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.serviceprovider')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('year'), descending=True), models.OrderBy(models.F('contractor__name'))],
            },
        ),
        migrations.CreateModel(
            name='ProviderEquipmentRequirementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('M', 'Mining'), ('S', 'Shipment')], max_length=1)),
                ('running', models.PositiveSmallIntegerField()),
                ('with_spare', models.PositiveSmallIntegerField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipmentclass')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.providerequipmentrequirement')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('activity')), models.OrderBy(models.F('equipment__name'))],
            },
        ),
        migrations.AddConstraint(
            model_name='providerequipmentrequirement',
            constraint=models.CheckConstraint(check=models.Q(('year__gt', 2023)), name='provider_equipment_requirement_min_year'),
        ),
        migrations.AddConstraint(
            model_name='providerequipmentrequirement',
            constraint=models.CheckConstraint(check=models.Q(('year__lt', 2050)), name='provider_equipment_requirement_max_year'),
        ),
        migrations.AddConstraint(
            model_name='providerequipmentrequirement',
            constraint=models.UniqueConstraint(fields=('contractor', 'year'), name='unique_provider_equipment_requirement'),
        ),
        migrations.AddConstraint(
            model_name='providerequipmentrequirementdetail',
            constraint=models.CheckConstraint(check=models.Q(('with_spare__gte', models.F('running'))), name='provider_equipment_requirement_spare_gte_running'),
        ),
        migrations.AddConstraint(
            model_name='providerequipmentrequirementdetail',
            constraint=models.UniqueConstraint(fields=('activity', 'equipment', 'requirement'), name='unique_equip'),
        ),
    ]
