# Generated by Django 4.2 on 2023-08-15 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_equipmentignitionstatus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentIdlingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.equipment')),
            ],
        ),
        migrations.AddIndex(
            model_name='equipmentidlingtime',
            index=models.Index(fields=['time_stamp'], name='fleet_equip_time_st_d2466a_idx'),
        ),
        migrations.AddConstraint(
            model_name='equipmentidlingtime',
            constraint=models.UniqueConstraint(fields=('equipment', 'time_stamp'), name='unique_equipment_idling_timestamp'),
        ),
    ]
