# Generated by Django 5.1.5 on 2026-03-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_breakdownstatus_causecode_componentcode_damagecode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentbreakdown',
            name='x_equipment_class',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
