# Generated by Django 5.1.5 on 2026-03-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_breakdownstatus_causecode_componentcode_damagecode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerequipmentregistry',
            name='tpl_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
