# Generated by Django 4.2 on 2023-08-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_equipmentidlingtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentidlingtime',
            name='duration',
        ),
        migrations.AddField(
            model_name='equipmentidlingtime',
            name='idling',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
