# Generated by Django 4.2.7 on 2024-04-17 04:00

import custom.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_providerequipmentregistry_x_contractor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentMobileNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('spaceless_number', custom.fields.SpaceLess(blank=True, max_length=20, null=True, unique=True)),
                ('equipment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.equipment')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('equipment__owner__name')), models.OrderBy(models.F('equipment__equipment_class__name')), models.OrderBy(models.F('equipment__fleet_number'))],
            },
        ),
    ]
