# Generated by Django 5.0.6 on 2024-06-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_providerequipmentrequirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerequipmentrequirementdetail',
            name='activity',
            field=models.CharField(choices=[('A', 'All'), ('M', 'Mining'), ('S', 'Shipment')], max_length=1),
        ),
    ]
