# Generated by Django 5.1.5 on 2026-03-27 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_equipmentbreakdown_x_equipment_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='InhouseEquipment',
            fields=[
            ],
            options={
                'verbose_name_plural': 'inhouse equipment units',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fleet.equipment',),
        ),
        migrations.AlterField(
            model_name='equipmentbreakdown',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet.inhouseequipment'),
        ),
    ]
