# Generated by Django 4.2 on 2023-08-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_remove_equipmentidlingtime_duration_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='equipmentidlingtime',
            index=models.Index(fields=['idling'], name='fleet_equip_idling_3c1beb_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentignitionstatus',
            index=models.Index(fields=['ignition'], name='fleet_equip_ignitio_f250aa_idx'),
        ),
    ]
