# Generated by Django 4.2.7 on 2024-06-05 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_equipmentmobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentmobilenumber',
            name='equipment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.equipment'),
        ),
        migrations.AlterField(
            model_name='providerequipmentregistry',
            name='capacity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet.capacity'),
        ),
    ]
