# Generated by Django 5.1.5 on 2026-03-30 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_inhouseequipment_alter_equipmentbreakdown_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerequipmentregistry',
            name='tpl_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
