# Generated by Django 4.2.7 on 2024-06-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_alter_equipmentmobilenumber_equipment_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='capacity',
            constraint=models.UniqueConstraint(fields=('unit_of_measure', 'value'), name='unique_equipment_capacity'),
        ),
    ]
