# Generated by Django 4.2 on 2023-08-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_equipmentidlingtime_fleet_equip_idling_3c1beb_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='equipmentclass',
            index=models.Index(fields=['name'], name='fleet_equip_name_abc154_idx'),
        ),
    ]
