# Generated by Django 4.2.7 on 2024-06-05 08:33

import custom.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_capacity_unique_equipment_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chassisserialnumber',
            name='name',
            field=custom.fields.AlphaNumeric(max_length=100, unique=True),
        ),
    ]
