# Generated by Django 4.2.7 on 2024-06-05 08:56

import custom.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_alter_chassisserialnumber_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineserialnumber',
            name='name',
            field=custom.fields.AlphaNumeric(max_length=100, unique=True),
        ),
    ]
