# Generated by Django 4.2.7 on 2024-06-06 01:18

import custom.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_alter_engineserialnumber_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platenumber',
            name='plate_number',
            field=custom.fields.AlphaNumeric(max_length=10, unique=True),
        ),
    ]
