GRANT ALL ON SCHEMA public  TO reader;
GRANT ALL ON SCHEMA staging TO reader;

GRANT REFERENCES ON ALL TABLES IN SCHEMA public  TO reader;
GRANT REFERENCES ON ALL TABLES IN SCHEMA staging TO reader;
GRANT SELECT     ON ALL TABLES IN SCHEMA public  TO reader;
GRANT SELECT     ON ALL TABLES IN SCHEMA staging TO reader;

