# Generated by Django 4.2 on 2023-05-27 03:49

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='block',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='inventory_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
