# Generated by Django 3.1.1 on 2020-09-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
