# Generated by Django 4.2 on 2023-08-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_block_inventory_name_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='co_lim',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='co_sap',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='density_br',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='density_lim',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='density_sap',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='fe_lim',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='fe_sap',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='mg',
            field=models.FloatField(default=0, help_text='Estimated magnesium content of the block in percent.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='mg_lim',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='mg_sap',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='ni_lim',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='ni_sap',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='pp_air',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='pp_br',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='pp_lim',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='pp_sap',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
