# Generated by Django 4.2 on 2023-10-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_block_co_lim_block_co_sap_block_density_br_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='co_lim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='co_sap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='density_br',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='density_lim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='density_sap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='fe_lim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='fe_sap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='mg',
            field=models.FloatField(blank=True, help_text='Estimated magnesium content of the block in percent.', null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='mg_lim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='mg_sap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='ni_lim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='ni_sap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='pp_air',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='pp_br',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='pp_lim',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='pp_sap',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
