# Generated by Django 3.0.3 on 2020-03-03 13:22

import custom.fields
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import sampling.models.sample


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('personnel', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.SpaceLess(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MiningSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_number', models.PositiveSmallIntegerField()),
                ('ridge', models.CharField(blank=True, max_length=2, null=True)),
                ('start_collection', models.DateField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(default=sampling.models.sample.this_year)),
                ('end_collection', models.DateField(blank=True, null=True)),
                ('trips', models.PositiveSmallIntegerField(default=0)),
                ('ready_for_delivery', models.BooleanField(default=False)),
                ('harvested', models.BooleanField(default=False)),
                ('dumping_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Stockyard')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.Material')),
            ],
            options={
                'ordering': ['-start_collection__year', '-series_number'],
            },
        ),
        migrations.CreateModel(
            name='PilingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TripsPerPile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effectivity', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('trips', models.PositiveSmallIntegerField()),
                ('piling_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.PilingMethod')),
            ],
            options={
                'ordering': ['-effectivity'],
            },
        ),
        migrations.CreateModel(
            name='MiningSampleReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_collected', models.CharField(choices=[('D', 'Day'), ('N', 'Night'), ('M', 'M')], max_length=1)),
                ('source', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3125)),
                ('dumping_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Stockyard')),
                ('foreman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managedminingsamplereport', to='personnel.Person')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.Material')),
                ('piling_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.PilingMethod')),
                ('sampler', models.ManyToManyField(blank=True, related_name='samplereport', to='personnel.Person')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisedminingsamplereport', to='personnel.Person')),
                ('tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.TrackedExcavator', verbose_name='TX')),
            ],
            options={
                'ordering': ['-date', '-shift_collected'],
            },
        ),
        migrations.CreateModel(
            name='MiningSampleIncrement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trips', models.PositiveSmallIntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.MiningSampleReport')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.MiningSample')),
            ],
            options={
                'ordering': ['sample__series_number'],
            },
        ),
        migrations.CreateModel(
            name='MiningSampleAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received_for_preparation', models.DateField(blank=True, null=True)),
                ('date_prepared', models.DateField(blank=True, null=True)),
                ('date_received_for_analysis', models.DateField(blank=True, null=True)),
                ('date_analyzed', models.DateField(blank=True, null=True)),
                ('ni', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Ni')),
                ('fe', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Fe')),
                ('co', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Co')),
                ('moisture', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%H₂O')),
                ('mining_sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assay', to='sampling.MiningSample')),
            ],
        ),
        migrations.AddField(
            model_name='miningsample',
            name='piling_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.PilingMethod'),
        ),
        migrations.AddConstraint(
            model_name='tripsperpile',
            constraint=models.CheckConstraint(check=models.Q(trips__gt=0), name='trips_min_1'),
        ),
        migrations.AddConstraint(
            model_name='miningsampleincrement',
            constraint=models.UniqueConstraint(fields=('sample', 'report'), name='sample_increment_report_constraint'),
        ),
        migrations.AddConstraint(
            model_name='miningsampleassay',
            constraint=models.CheckConstraint(check=models.Q(ni__lte=100), name='ni_max_100'),
        ),
        migrations.AddConstraint(
            model_name='miningsampleassay',
            constraint=models.CheckConstraint(check=models.Q(fe__lte=100), name='fe_max_100'),
        ),
        migrations.AddConstraint(
            model_name='miningsampleassay',
            constraint=models.CheckConstraint(check=models.Q(co__lte=100), name='co_max_100'),
        ),
        migrations.AddConstraint(
            model_name='miningsampleassay',
            constraint=models.CheckConstraint(check=models.Q(moisture__lte=100), name='moisture_max_100'),
        ),
        migrations.AddConstraint(
            model_name='miningsampleassay',
            constraint=models.CheckConstraint(check=models.Q(ni__gte=0), name='ni_min_0'),
        ),
        migrations.AddConstraint(
            model_name='miningsampleassay',
            constraint=models.CheckConstraint(check=models.Q(fe__gte=0), name='fe_min_0'),
        ),
        migrations.AddConstraint(
            model_name='miningsampleassay',
            constraint=models.CheckConstraint(check=models.Q(co__gte=0), name='co_min_0'),
        ),
        migrations.AddConstraint(
            model_name='miningsampleassay',
            constraint=models.CheckConstraint(check=models.Q(moisture__gte=0), name='moisture_min_0'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.UniqueConstraint(fields=('ridge', 'year', 'piling_method', 'series_number'), name='mining_sample_series_constraint'),
        ),
    ]
