# Generated by Django 4.0.4 on 2022-05-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillcoresample',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Cu'),
        ),
        migrations.AddField(
            model_name='miningsample',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Cu'),
        ),
        migrations.AddField(
            model_name='shipmentdischargeassay',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Cu'),
        ),
        migrations.AddField(
            model_name='shipmentdischargelotassay',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Cu'),
        ),
        migrations.AddField(
            model_name='shipmentloadingassay',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Cu'),
        ),
        migrations.AddField(
            model_name='shipmentloadinglotassay',
            name='cu',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Cu'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(('cr2o3__lte', 100)), name='cr2o3_max_100_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(('cu__lte', 100)), name='cu_max_100_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(('cr2o3__gte', 0)), name='cr2o3_min_0_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(('cu__gte', 0)), name='cu_min_0_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(('cr2o3__lte', 100)), name='cr2o3_max_100_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(('cu__lte', 100)), name='cu_max_100_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(('cr2o3__gte', 0)), name='cr2o3_min_0_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(('cu__gte', 0)), name='cu_min_0_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(('cr2o3__lte', 100)), name='cr2o3_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(('cu__lte', 100)), name='cu_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(('cr2o3__gte', 0)), name='cr2o3_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(('cu__gte', 0)), name='cu_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(('cr2o3__lte', 100)), name='cr2o3_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(('cu__lte', 100)), name='cu_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(('cr2o3__gte', 0)), name='cr2o3_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(('cu__gte', 0)), name='cu_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(('cr2o3__lte', 100)), name='cr2o3_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(('cu__lte', 100)), name='cu_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(('cr2o3__gte', 0)), name='cr2o3_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(('cu__gte', 0)), name='cu_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(('cr2o3__lte', 100)), name='cr2o3_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(('cu__lte', 100)), name='cu_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(('cr2o3__gte', 0)), name='cr2o3_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(('cu__gte', 0)), name='cu_min_0_loadinglotassay'),
        ),
    ]
