# Generated by Django 4.0 on 2022-04-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedshipmentloadingassay',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='assay/shipment/loading/'),
        ),
    ]
