# Generated by Django 4.1.7 on 2023-04-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedshipmentloadingassay',
            name='mgb_receipt',
            field=models.FileField(blank=True, null=True, upload_to='assay/shipment/loading_receipt'),
        ),
    ]
