# Generated by Django 4.2 on 2023-10-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillcoresample',
            name='tio2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%TiO₂'),
        ),
        migrations.AddField(
            model_name='miningsample',
            name='tio2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%TiO₂'),
        ),
        migrations.AddField(
            model_name='shipmentdischargeassay',
            name='tio2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%TiO₂'),
        ),
        migrations.AddField(
            model_name='shipmentdischargelotassay',
            name='tio2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%TiO₂'),
        ),
        migrations.AddField(
            model_name='shipmentloadingassay',
            name='tio2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%TiO₂'),
        ),
        migrations.AddField(
            model_name='shipmentloadinglotassay',
            name='tio2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%TiO₂'),
        ),
    ]
