# Generated by Django 3.0.7 on 2020-08-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillcoresample',
            name='cr2o3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Cr₂O₃'),
        ),
        migrations.AddField(
            model_name='miningsample',
            name='cr2o3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Cr₂O₃'),
        ),
        migrations.AddField(
            model_name='shipmentdischargeassay',
            name='cr2o3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Cr₂O₃'),
        ),
        migrations.AddField(
            model_name='shipmentdischargelotassay',
            name='cr2o3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Cr₂O₃'),
        ),
        migrations.AddField(
            model_name='shipmentloadingassay',
            name='cr2o3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Cr₂O₃'),
        ),
        migrations.AddField(
            model_name='shipmentloadinglotassay',
            name='cr2o3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Cr₂O₃'),
        ),
    ]
