# Generated by Django 3.0.3 on 2020-03-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillcoresample',
            name='excavated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
