# Generated by Django 3.0.7 on 2020-08-01 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentloadingassay',
            name='chemist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ApprovedShipmentLoadingAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('assay', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sampling.ShipmentLoadingAssay')),
            ],
        ),
    ]
