# Generated by Django 3.0.7 on 2020-07-29 02:48

import custom.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_auto_20200729_1048'),
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'laboratories',
            },
        ),
        migrations.CreateModel(
            name='ShipmentDischargeAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received_for_preparation', models.DateField(blank=True, null=True)),
                ('date_prepared', models.DateField(blank=True, null=True)),
                ('date_received_for_analysis', models.DateField(blank=True, null=True)),
                ('date_analyzed', models.DateField(blank=True, null=True)),
                ('al', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Al')),
                ('al2o3', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Al₂O₃')),
                ('c', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%C')),
                ('cao', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%CaO')),
                ('co', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Co')),
                ('cr', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Cr')),
                ('fe', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Fe')),
                ('mg', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Mg')),
                ('mgo', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%MgO')),
                ('mn', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Mn')),
                ('ni', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Ni')),
                ('p', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%P')),
                ('s', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%S')),
                ('sc', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Sc')),
                ('si', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Si')),
                ('sio2', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%SiO₂')),
                ('ignition_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('moisture', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%H₂O')),
                ('wmt', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='WMT')),
                ('dmt', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='DMT')),
            ],
            options={
                'ordering': ['-shipment__laydaysstatement__completed_loading'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentDischargeLotAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received_for_preparation', models.DateField(blank=True, null=True)),
                ('date_prepared', models.DateField(blank=True, null=True)),
                ('date_received_for_analysis', models.DateField(blank=True, null=True)),
                ('date_analyzed', models.DateField(blank=True, null=True)),
                ('al', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Al')),
                ('al2o3', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Al₂O₃')),
                ('c', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%C')),
                ('cao', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%CaO')),
                ('co', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Co')),
                ('cr', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Cr')),
                ('fe', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Fe')),
                ('mg', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Mg')),
                ('mgo', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%MgO')),
                ('mn', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Mn')),
                ('ni', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Ni')),
                ('p', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%P')),
                ('s', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%S')),
                ('sc', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Sc')),
                ('si', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Si')),
                ('sio2', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%SiO₂')),
                ('ignition_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('moisture', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%H₂O')),
                ('lot', models.PositiveSmallIntegerField(unique=True)),
                ('wmt', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='WMT')),
            ],
            options={
                'ordering': ['lot'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLoadingAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received_for_preparation', models.DateField(blank=True, null=True)),
                ('date_prepared', models.DateField(blank=True, null=True)),
                ('date_received_for_analysis', models.DateField(blank=True, null=True)),
                ('date_analyzed', models.DateField(blank=True, null=True)),
                ('al', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Al')),
                ('al2o3', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Al₂O₃')),
                ('c', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%C')),
                ('cao', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%CaO')),
                ('co', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Co')),
                ('cr', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Cr')),
                ('fe', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Fe')),
                ('mg', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Mg')),
                ('mgo', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%MgO')),
                ('mn', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Mn')),
                ('ni', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Ni')),
                ('p', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%P')),
                ('s', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%S')),
                ('sc', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Sc')),
                ('si', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Si')),
                ('sio2', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%SiO₂')),
                ('ignition_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('moisture', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%H₂O')),
                ('date', models.DateField()),
                ('wmt', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='WMT')),
                ('dmt', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='DMT')),
                ('ni_ton', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Ni-ton')),
            ],
            options={
                'ordering': ['-shipment__laydaysstatement__completed_loading'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLoadingLotAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received_for_preparation', models.DateField(blank=True, null=True)),
                ('date_prepared', models.DateField(blank=True, null=True)),
                ('date_received_for_analysis', models.DateField(blank=True, null=True)),
                ('date_analyzed', models.DateField(blank=True, null=True)),
                ('al', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Al')),
                ('al2o3', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Al₂O₃')),
                ('c', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%C')),
                ('cao', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%CaO')),
                ('co', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Co')),
                ('cr', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Cr')),
                ('fe', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Fe')),
                ('mg', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Mg')),
                ('mgo', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%MgO')),
                ('mn', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Mn')),
                ('ni', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Ni')),
                ('p', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%P')),
                ('s', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%S')),
                ('sc', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Sc')),
                ('si', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Si')),
                ('sio2', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%SiO₂')),
                ('ignition_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('moisture', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%H₂O')),
                ('lot', models.PositiveSmallIntegerField(unique=True)),
                ('wmt', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='WMT')),
            ],
            options={
                'ordering': ['lot'],
            },
        ),
        migrations.AlterModelOptions(
            name='lithology',
            options={'verbose_name_plural': 'lithologies'},
        ),
        migrations.AddField(
            model_name='drillcoresample',
            name='al2o3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Al₂O₃'),
        ),
        migrations.AddField(
            model_name='drillcoresample',
            name='cao',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%CaO'),
        ),
        migrations.AddField(
            model_name='drillcoresample',
            name='ignition_loss',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='drillcoresample',
            name='mgo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%MgO'),
        ),
        migrations.AddField(
            model_name='drillcoresample',
            name='mn',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Mn'),
        ),
        migrations.AddField(
            model_name='drillcoresample',
            name='p',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%P'),
        ),
        migrations.AddField(
            model_name='drillcoresample',
            name='s',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%S'),
        ),
        migrations.AddField(
            model_name='drillcoresample',
            name='sio2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%SiO₂'),
        ),
        migrations.AddField(
            model_name='miningsample',
            name='al2o3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Al₂O₃'),
        ),
        migrations.AddField(
            model_name='miningsample',
            name='cao',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%CaO'),
        ),
        migrations.AddField(
            model_name='miningsample',
            name='ignition_loss',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='miningsample',
            name='mgo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%MgO'),
        ),
        migrations.AddField(
            model_name='miningsample',
            name='mn',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%Mn'),
        ),
        migrations.AddField(
            model_name='miningsample',
            name='p',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%P'),
        ),
        migrations.AddField(
            model_name='miningsample',
            name='s',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%S'),
        ),
        migrations.AddField(
            model_name='miningsample',
            name='sio2',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%SiO₂'),
        ),
        migrations.AlterField(
            model_name='lithology',
            name='name',
            field=custom.fields.NameField(max_length=20, unique=True),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(al2o3__lte=100), name='al2o3_max_100_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(cao__lte=100), name='cao_max_100_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(mgo__lte=100), name='mgo_max_100_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(mn__lte=100), name='mn_max_100_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(p__lte=100), name='p_max_100_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(s__lte=100), name='s_max_100_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(sio2__lte=100), name='sio2_max_100_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(ignition_loss__lte=100), name='ignition_loss_max_100_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(al2o3__gte=0), name='al2o3_min_0_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(cao__gte=0), name='cao_min_0_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(mgo__gte=0), name='mgo_min_0_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(mn__gte=0), name='mn_min_0_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(p__gte=0), name='p_min_0_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(s__gte=0), name='s_min_0_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(sio2__gte=0), name='sio2_min_0_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(ignition_loss__gte=0), name='ignition_loss_min_0_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(al2o3__lte=100), name='al2o3_max_100_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(cao__lte=100), name='cao_max_100_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(mgo__lte=100), name='mgo_max_100_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(mn__lte=100), name='mn_max_100_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(p__lte=100), name='p_max_100_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(s__lte=100), name='s_max_100_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(sio2__lte=100), name='sio2_max_100_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(ignition_loss__lte=100), name='ignition_loss_max_100_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(al2o3__gte=0), name='al2o3_min_0_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(cao__gte=0), name='cao_min_0_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(mgo__gte=0), name='mgo_min_0_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(mn__gte=0), name='mn_min_0_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(p__gte=0), name='p_min_0_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(s__gte=0), name='s_min_0_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(sio2__gte=0), name='sio2_min_0_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(ignition_loss__gte=0), name='ignition_loss_min_0_miningsample'),
        ),
        migrations.AddField(
            model_name='shipmentloadinglotassay',
            name='shipment_assay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.ShipmentLoadingAssay'),
        ),
        migrations.AddField(
            model_name='shipmentloadingassay',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipment.Shipment'),
        ),
        migrations.AddField(
            model_name='shipmentdischargelotassay',
            name='shipment_assay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampling.ShipmentDischargeAssay'),
        ),
        migrations.AddField(
            model_name='shipmentdischargeassay',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sampling.Laboratory'),
        ),
        migrations.AddField(
            model_name='shipmentdischargeassay',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shipment.Shipment'),
        ),
        migrations.CreateModel(
            name='ChinaShipmentAssay',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sampling.shipmentdischargeassay',),
        ),
        migrations.CreateModel(
            name='PamcoShipmentAssay',
            fields=[
            ],
            options={
                'verbose_name': 'PAMCO Shipment Assay',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sampling.shipmentdischargeassay',),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(al__lte=100), name='al_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(al2o3__lte=100), name='al2o3_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(c__lte=100), name='c_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(cao__lte=100), name='cao_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(co__lte=100), name='co_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(cr__lte=100), name='cr_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(fe__lte=100), name='fe_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(mg__lte=100), name='mg_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(mgo__lte=100), name='mgo_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(mn__lte=100), name='mn_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(ni__lte=100), name='ni_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(p__lte=100), name='p_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(s__lte=100), name='s_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(sc__lte=100), name='sc_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(si__lte=100), name='si_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(sio2__lte=100), name='sio2_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(ignition_loss__lte=100), name='ignition_loss_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(moisture__lte=100), name='moisture_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(al__gte=0), name='al_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(al2o3__gte=0), name='al2o3_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(c__gte=0), name='c_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(cao__gte=0), name='cao_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(co__gte=0), name='co_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(cr__gte=0), name='cr_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(fe__gte=0), name='fe_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(mg__gte=0), name='mg_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(mgo__gte=0), name='mgo_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(mn__gte=0), name='mn_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(ni__gte=0), name='ni_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(p__gte=0), name='p_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(s__gte=0), name='s_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(sc__gte=0), name='sc_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(si__gte=0), name='si_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(sio2__gte=0), name='sio2_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(ignition_loss__gte=0), name='ignition_loss_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(moisture__gte=0), name='moisture_min_0_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(al__lte=100), name='al_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(al2o3__lte=100), name='al2o3_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(c__lte=100), name='c_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(cao__lte=100), name='cao_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(co__lte=100), name='co_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(cr__lte=100), name='cr_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(fe__lte=100), name='fe_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(mg__lte=100), name='mg_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(mgo__lte=100), name='mgo_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(mn__lte=100), name='mn_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(ni__lte=100), name='ni_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(p__lte=100), name='p_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(s__lte=100), name='s_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(sc__lte=100), name='sc_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(si__lte=100), name='si_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(sio2__lte=100), name='sio2_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(ignition_loss__lte=100), name='ignition_loss_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(moisture__lte=100), name='moisture_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(al__gte=0), name='al_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(al2o3__gte=0), name='al2o3_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(c__gte=0), name='c_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(cao__gte=0), name='cao_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(co__gte=0), name='co_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(cr__gte=0), name='cr_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(fe__gte=0), name='fe_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(mg__gte=0), name='mg_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(mgo__gte=0), name='mgo_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(mn__gte=0), name='mn_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(ni__gte=0), name='ni_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(p__gte=0), name='p_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(s__gte=0), name='s_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(sc__gte=0), name='sc_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(si__gte=0), name='si_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(sio2__gte=0), name='sio2_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(ignition_loss__gte=0), name='ignition_loss_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(moisture__gte=0), name='moisture_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(al__lte=100), name='al_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(al2o3__lte=100), name='al2o3_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(c__lte=100), name='c_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(cao__lte=100), name='cao_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(co__lte=100), name='co_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(cr__lte=100), name='cr_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(fe__lte=100), name='fe_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(mg__lte=100), name='mg_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(mgo__lte=100), name='mgo_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(mn__lte=100), name='mn_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(ni__lte=100), name='ni_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(p__lte=100), name='p_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(s__lte=100), name='s_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(sc__lte=100), name='sc_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(si__lte=100), name='si_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(sio2__lte=100), name='sio2_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(ignition_loss__lte=100), name='ignition_loss_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(moisture__lte=100), name='moisture_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(al__gte=0), name='al_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(al2o3__gte=0), name='al2o3_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(c__gte=0), name='c_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(cao__gte=0), name='cao_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(co__gte=0), name='co_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(cr__gte=0), name='cr_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(fe__gte=0), name='fe_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(mg__gte=0), name='mg_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(mgo__gte=0), name='mgo_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(mn__gte=0), name='mn_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(ni__gte=0), name='ni_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(p__gte=0), name='p_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(s__gte=0), name='s_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(sc__gte=0), name='sc_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(si__gte=0), name='si_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(sio2__gte=0), name='sio2_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(ignition_loss__gte=0), name='ignition_loss_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(moisture__gte=0), name='moisture_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(al__lte=100), name='al_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(al2o3__lte=100), name='al2o3_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(c__lte=100), name='c_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(cao__lte=100), name='cao_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(co__lte=100), name='co_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(cr__lte=100), name='cr_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(fe__lte=100), name='fe_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(mg__lte=100), name='mg_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(mgo__lte=100), name='mgo_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(mn__lte=100), name='mn_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(ni__lte=100), name='ni_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(p__lte=100), name='p_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(s__lte=100), name='s_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(sc__lte=100), name='sc_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(si__lte=100), name='si_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(sio2__lte=100), name='sio2_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(ignition_loss__lte=100), name='ignition_loss_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(moisture__lte=100), name='moisture_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(al__gte=0), name='al_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(al2o3__gte=0), name='al2o3_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(c__gte=0), name='c_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(cao__gte=0), name='cao_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(co__gte=0), name='co_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(cr__gte=0), name='cr_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(fe__gte=0), name='fe_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(mg__gte=0), name='mg_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(mgo__gte=0), name='mgo_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(mn__gte=0), name='mn_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(ni__gte=0), name='ni_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(p__gte=0), name='p_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(s__gte=0), name='s_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(sc__gte=0), name='sc_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(si__gte=0), name='si_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(sio2__gte=0), name='sio2_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(ignition_loss__gte=0), name='ignition_loss_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(moisture__gte=0), name='moisture_min_0_dischargeassay'),
        ),
    ]
