# Generated by Django 3.2 on 2021-06-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillcoresample',
            name='arsenic',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%As'),
        ),
        migrations.AddField(
            model_name='miningsample',
            name='arsenic',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%As'),
        ),
        migrations.AddField(
            model_name='shipmentdischargeassay',
            name='arsenic',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%As'),
        ),
        migrations.AddField(
            model_name='shipmentdischargelotassay',
            name='arsenic',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%As'),
        ),
        migrations.AddField(
            model_name='shipmentloadingassay',
            name='arsenic',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%As'),
        ),
        migrations.AddField(
            model_name='shipmentloadinglotassay',
            name='arsenic',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='%As'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(arsenic__lte=100), name='arsenic_max_100_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='drillcoresample',
            constraint=models.CheckConstraint(check=models.Q(arsenic__gte=0), name='arsenic_min_0_drillcore'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(arsenic__lte=100), name='arsenic_max_100_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='miningsample',
            constraint=models.CheckConstraint(check=models.Q(arsenic__gte=0), name='arsenic_min_0_miningsample'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(arsenic__lte=100), name='arsenic_max_100_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargeassay',
            constraint=models.CheckConstraint(check=models.Q(arsenic__gte=0), name='arsenic_min_0_dischargeassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(arsenic__lte=100), name='arsenic_max_100_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.CheckConstraint(check=models.Q(arsenic__gte=0), name='arsenic_min_0_dischargelotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(arsenic__lte=100), name='arsenic_max_100_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadingassay',
            constraint=models.CheckConstraint(check=models.Q(arsenic__gte=0), name='arsenic_min_0_loadingassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(arsenic__lte=100), name='arsenic_max_100_loadinglotassay'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.CheckConstraint(check=models.Q(arsenic__gte=0), name='arsenic_min_0_loadinglotassay'),
        ),
    ]
