# Generated by Django 3.0.7 on 2020-07-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0002_auto_20200729_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chinashipmentassay',
            options={'verbose_name': 'China Shipment Discharge Assay'},
        ),
        migrations.AlterModelOptions(
            name='pamcoshipmentassay',
            options={'verbose_name': 'PAMCO Shipment Discharge Assay'},
        ),
        migrations.AlterField(
            model_name='shipmentloadinglotassay',
            name='lot',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='shipmentdischargelotassay',
            constraint=models.UniqueConstraint(fields=('shipment_assay', 'lot'), name='unique_pamco_assay_lot'),
        ),
        migrations.AddConstraint(
            model_name='shipmentloadinglotassay',
            constraint=models.UniqueConstraint(fields=('shipment_assay', 'lot'), name='unique_loading_assay_lot'),
        ),
    ]
