# Generated by Django 3.1.1 on 2020-10-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0002_drillcoresample_lithology_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillcoresample',
            name='lithology_modified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drillcore', to='sampling.lithology'),
        ),
    ]
