# Generated by Django 4.0 on 2022-04-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0002_approvedshipmentloadingassay_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedshipmentdischargeassay',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='assay/shipment/discharing/'),
        ),
    ]
