# Generated by Django 3.0.7 on 2020-08-09 08:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0002_auto_20200803_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedShipmentDischargeAssay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField()),
                ('assay', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sampling.ShipmentDischargeAssay')),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('approved'), nulls_first=True), '-assay__shipment__laydaysstatement__completed_loading'],
            },
        ),
    ]
