# Generated by Django 3.0.7 on 2020-07-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0003_auto_20200729_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentdischargeassay',
            name='ni_ton',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Ni-ton'),
        ),
        migrations.AlterField(
            model_name='shipmentdischargelotassay',
            name='lot',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
