#!/usr/bin/bash

if [[ "${UID}" -ne 0 ]]
then
  echo "This script must be run as root or with sudo."
  exit 1
fi

function print_help
{
  echo '
Reset SELinux policy modules of `myapp` using the file `myapp.te`.
This program expects that `myapp.te` file exists.

Usage:
### Using sudo
$ sudo reset_policy myapp.te

### As root
# reset_policy myapp.te
'
}

if [ $# -eq 0 ]
then
    printf "No arguments detetected!\n\n"
    print_help
    exit 1
elif [ $# -gt 1 ]
then
    echo "Too many arguments!"
    print_help
    exit 1
elif [[ ! $1  =~ .*\.te$  ]]
then
    echo "$1 is not a .te file!"
    print_help
    exit 1
elif [ ! -f $1 ]
then
    echo "$1 does not exists!"
    print_help
    exit 0
else
    te=$1
    app=${te%.*}
    mod=$app.mod
    pp=$app.pp
    echo "Checking type enforcement file..." && \
        checkmodule -M -m -o $mod $te && \
        echo "Packaging SELinux module..." && \
        semodule_package -o $pp -m $mod && \
        echo "Installing module..." && \
        semodule -i $pp && \
        rm -f $mod $pp && \
        echo "Done."
    exit 0
fi
