# Generated by Django 4.2 on 2023-05-12 07:20

import camp_admin.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0002_alter_equipment_month_of_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField(null=True)),
                ('date_expiry', models.DateField(blank=True, help_text='Leave blank if expiry is exactly a year from registration', null=True)),
                ('registration_scan', models.FileField(blank=True, null=True, upload_to=camp_admin.functions.filepath)),
            ],
        ),
        migrations.CreateModel(
            name='VehicularInsurance',
            fields=[
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='fleet.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Floater',
            fields=[
                ('insurance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='camp_admin.insurance')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp_admin.vehicularinsurance')),
            ],
            bases=('camp_admin.insurance',),
        ),
        migrations.CreateModel(
            name='CTPL',
            fields=[
                ('insurance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='camp_admin.insurance')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp_admin.vehicularinsurance')),
            ],
            bases=('camp_admin.insurance',),
        ),
        migrations.CreateModel(
            name='Comprehensive',
            fields=[
                ('insurance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='camp_admin.insurance')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp_admin.vehicularinsurance')),
            ],
            bases=('camp_admin.insurance',),
        ),
    ]
