# Generated by Django 5.0.6 on 2024-06-06 10:17

import camp_admin.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateField(null=True)),
                ('date_expiry', models.DateField(blank=True, help_text='Leave blank if expiry is exactly a year from registration', null=True)),
                ('registration_scan', models.FileField(blank=True, null=True, upload_to=camp_admin.functions.filepath)),
            ],
        ),
    ]
