# Generated by Django 5.0.6 on 2024-06-06 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camp_admin', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicularInsurance',
            fields=[
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='fleet.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Comprehensive',
            fields=[
                ('insurance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='camp_admin.insurance')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp_admin.vehicularinsurance')),
            ],
            bases=('camp_admin.insurance',),
        ),
        migrations.CreateModel(
            name='CTPL',
            fields=[
                ('insurance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='camp_admin.insurance')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp_admin.vehicularinsurance')),
            ],
            bases=('camp_admin.insurance',),
        ),
        migrations.CreateModel(
            name='Floater',
            fields=[
                ('insurance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='camp_admin.insurance')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp_admin.vehicularinsurance')),
            ],
            bases=('camp_admin.insurance',),
        ),
    ]
