# Generated by Django 4.2 on 2023-05-22 06:12

from django.db import migrations, models
import ormm.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCommunication',
            fields=[
                ('transmittal_number', models.CharField(blank=True, max_length=13, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('nature_of_content', models.TextField(blank=True, max_length=99, null=True)),
                ('receiving_copy', models.FileField(blank=True, null=True, upload_to=ormm.functions.filepath)),
            ],
        ),
    ]
