# Generated by Django 4.2.7 on 2023-11-13 03:47

from django.db import migrations, models
import django.db.models.deletion
import ormm.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIncomingCommunication',
            fields=[
                ('transmittal_number', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('datetime_received', models.DateTimeField(null=True)),
                ('sender', models.CharField(max_length=99, null=True)),
                ('subject', models.TextField(max_length=499, null=True)),
                ('scan', models.FileField(blank=True, null=True, upload_to=ormm.functions.filepath_extincomingcomm)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalCommunication',
            fields=[
                ('transmittal_number', models.CharField(blank=True, max_length=13, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('nature_of_content', models.TextField(blank=True, max_length=99, null=True)),
                ('recipient', models.CharField(default='', max_length=30)),
                ('receiving_copy', models.FileField(blank=True, null=True, upload_to=ormm.functions.filepath)),
                ('cancel', models.BooleanField(default=False)),
                ('requesting_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organizationunit')),
            ],
        ),
    ]
