# Generated by Django 4.2 on 2023-05-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcommunication',
            name='recipient',
            field=models.CharField(default='', max_length=30),
        ),
    ]
