# Generated by Django 4.2 on 2023-05-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormm', '0002_externalcommunication_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcommunication',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
