# Generated by Django 4.2 on 2023-05-30 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('ormm', '0003_externalcommunication_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalcommunication',
            name='requesting_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organizationunit'),
        ),
    ]
