# Generated by Django 4.2 on 2023-05-31 06:13

from django.db import migrations, models
import ormm.functions


class Migration(migrations.Migration):

    dependencies = [
        ('ormm', '0004_externalcommunication_requesting_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIncomingCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_received', models.DateTimeField(null=True)),
                ('sender', models.CharField(max_length=30, null=True)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('scan', models.FileField(blank=True, null=True, upload_to=ormm.functions.filepath_extincomingcomm)),
            ],
        ),
    ]
