# Generated by Django 4.2 on 2023-10-16 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormm', '0005_externalincomingcommunication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalIncomingCommunication',
        ),
    ]
