# Generated by Django 4.2 on 2023-10-16 01:47

from django.db import migrations, models
import ormm.functions


class Migration(migrations.Migration):

    dependencies = [
        ('ormm', '0006_delete_externalincomingcommunication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIncomingCommunication',
            fields=[
                ('transmittal_number', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('datetime_received', models.DateTimeField(null=True)),
                ('sender', models.CharField(max_length=30, null=True)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('scan', models.FileField(blank=True, null=True, upload_to=ormm.functions.filepath_extincomingcomm)),
            ],
        ),
    ]
