# Generated by Django 4.2 on 2023-10-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormm', '0007_externalincomingcommunication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalincomingcommunication',
            name='sender',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='externalincomingcommunication',
            name='subject',
            field=models.TextField(max_length=499, null=True),
        ),
    ]
