# Generated by Django 5.0.6 on 2024-07-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsocketListener',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
    ]
