# Generated by Django 4.0.6 on 2022-07-12 03:51

import custom.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_suffix',
            field=custom.fields.NameField(blank=True, help_text='Junior, Senior, III, etc.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Non-binary')], max_length=1, null=True),
        ),
    ]
