# Generated by Django 4.1.7 on 2023-03-27 05:25

import custom.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='pic',
            field=custom.fields.AlphaNumeric(blank=True, help_text='Professional Identification Card Number', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='custom.profession'),
        ),
    ]
