# Generated by Django 4.0.6 on 2022-08-17 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('custom', '0002_user_name_suffix_user_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_number', models.CharField(blank=True, choices=[('222', '222'), ('8080', '8080')], help_text='If this field is set, the number and group fields are ignored. This is used in sending SMS to the network provider.', max_length=4, null=True)),
                ('sms', models.TextField(blank=True, help_text='Text message to be sent. Message shall only be sent if recipient is not empty.', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('group', models.ManyToManyField(blank=True, help_text='If either provider_number or number field is not empty, this field is ignored.<br/>', to='auth.group')),
                ('number', models.ManyToManyField(blank=True, help_text='If this field is not empty, the group field is ignored.<br/>', to='custom.mobilenumber')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('modified'), descending=True)],
            },
        ),
    ]
