# Generated by Django 4.1.7 on 2023-03-27 23:55

import custom.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_profession_user_pic_user_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
        migrations.CreateModel(
            name='ProfessionalIdentificationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', custom.fields.AlphaNumeric(max_length=8)),
                ('date_registered', models.DateField(blank=True, null=True)),
                ('date_expiry', models.DateField(blank=True, null=True)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom.profession')),
            ],
        ),
    ]
