# Generated by Django 4.2.7 on 2024-04-12 04:44

import custom.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_groupmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', custom.fields.NameField(max_length=40, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
