# Generated by Django 5.0.6 on 2024-07-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_websocketlistener'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websocketlistener',
            name='start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
