# Generated by Django 4.0.6 on 2022-08-20 00:18

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_textmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilenumber',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('user__username')), django.db.models.expressions.OrderBy(django.db.models.expressions.F('spaceless_number'))]},
        ),
    ]
