# Generated by Django 4.2.7 on 2024-04-15 10:15

import custom.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_unitofmeasure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='name',
            field=custom.fields.NameFieldWithSmallCase(max_length=40, unique=True),
        ),
    ]
