# Generated by Django 4.0.4 on 2022-04-22 21:58

import custom.fields
from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_alter_mobilenumber_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilenumber',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('spaceless_number'))]},
        ),
        migrations.AddField(
            model_name='mobilenumber',
            name='spaceless_number',
            field=custom.fields.SpaceLess(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
