# Generated by Django 4.2.7 on 2024-05-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0004_alter_unitofmeasure_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Linux User ID', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vnc_id',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tiger VNC Port', null=True, unique=True),
        ),
    ]
