# Generated by Django 4.0.4 on 2022-04-30 13:45

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0005_log'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('created'), descending=True)]},
        ),
    ]
